//! `host_ports` — the console asks the shell which ports it actually bound the sidecars on, rather
//! than a port baked at BUILD time (`VITE_API_URL`). The packaged app's daemon boots on a candidate
//! from `config/ports.ts` chosen at RUNTIME (`sidecars::resolve_ports` — the first free one wins),
//! so no port is knowable until the shell has actually tried; the console's `HostInfoService`
//! (`packages/app/react/src/services/HostInfoService`) is the one place it asks (spec 2026-08-25/26).
//!
//! Same command shape as `window.rs` / `system_preconditions.rs`: `#[tauri::command]` +
//! `#[specta::specta]`, collected once in `super::specta_builder()`, TS bindings regenerated by
//! `cargo test`. `core:default` already covers `invoke`, so `hostInfo` carries an empty permission
//! list (`config/capabilities.ts`).

/// The resolved ports, managed as `tauri::State<ResolvedPorts>` from `lib.rs`'s `setup` — set
/// EXACTLY ONCE, right after `sidecars::resolve_ports` runs, so this command can only ever answer
/// with the SAME ports the spawned sidecars (or the boot-error splash's failure list) got.
pub struct ResolvedPorts {
    pub api: u16,
    pub channel: u16,
}

/// What crosses to the console. `api_port` is the one the react `Config` actually needs
/// (`serviceBaseUrls.typescript` / `.go` both resolve through the daemon — the browser never talks
/// to the gateway directly, see `packages/app/react/src/lib/config.ts`); `channel_port` rides along
/// for diagnostics/symmetry with what the shell resolved.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct HostPorts {
    pub api_port: u16,
    pub channel_port: u16,
}

#[tauri::command]
#[specta::specta]
pub fn host_ports(ports: tauri::State<'_, ResolvedPorts>) -> HostPorts {
    HostPorts { api_port: ports.api, channel_port: ports.channel }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The wire shape the react port declares BY HAND (`HostInfoService.ts` composes
    /// `http://127.0.0.1:${apiPort}` from this) — pinned here so a serde rename on this side fails
    /// in `cargo test`, not in the console at runtime.
    #[test]
    fn the_payload_is_camel_case() {
        let json = serde_json::to_value(HostPorts { api_port: 47330, channel_port: 47332 }).expect("serialize");
        assert_eq!(json, serde_json::json!({ "apiPort": 47330, "channelPort": 47332 }));
    }
}
