//! `window_chrome` — what this host draws around the webview, so the console can lay out its
//! integrated title bar (react `AppChrome`) against a FACT instead of a platform name.
//!
//! `config/window.ts` declares `titleBarStyle: 'Overlay'` for the main window. Tauri honours that
//! on macOS only: there the OS traffic lights are overlaid top-left ON the webview, and the console
//! has to keep its wordmark clear of them. On Windows and Linux the same config yields a NATIVE
//! decorated title bar ABOVE the webview — min/max/close come from the OS, and a reserved band in
//! the console would be dead space under nothing.
//!
//! The answer is derived, not hardcoded: the calling window's declared `title_bar_style` (read off
//! the same generated config the shell was built from — never a `"main"` literal, the special
//! `tauri::Window` argument names the caller) crossed with the declared `Platform` vocabulary from
//! `crate::system_preconditions` — the same closed enum `full_disk_access.rs` consumes; no stringly
//! OS names. `chrome_for` is the pure core so all three hosts are provable on any one of them.
//!
//! Same command shape as `secrets.rs` / `system_preconditions.rs`: `#[tauri::command]` +
//! `#[specta::specta]`, collected once in `super::specta_builder()`, TS bindings regenerated by
//! `cargo test`. `core:default` covers `invoke`, so the capability key is declared with an empty
//! permission list (`config/capabilities.ts` `windowChrome: []`).

use tauri::utils::TitleBarStyle;

use crate::system_preconditions::{current_platform, Platform};

/// Who draws the window controls, from the webview's point of view.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, specta::Type)]
#[serde(rename_all = "lowercase")]
pub enum TitleBar {
    /// The OS overlays its controls ON the webview (macOS `titleBarStyle: Overlay`): the console
    /// owns the full window height and must reserve the traffic-light band.
    Overlay,
    /// The OS draws a decorated title bar ABOVE the webview (Windows, Linux — or any window that
    /// did not ask for Overlay): nothing overlaps the console, nothing to reserve.
    Native,
}

/// What crosses to the console — mirrors the react port `WindowService.chrome()` verbatim
/// (`{ titleBar: 'overlay' | 'native' }`); the serde test below pins that shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct WindowChrome {
    pub title_bar: TitleBar,
}

/// PURE — the decision, testable for every host on any host. Overlay iff the window DECLARED it
/// and the platform is the one that honours it (`Platform::Macos` — the closed vocabulary
/// `system_preconditions` declares; a new platform extends the enum, never a string compare).
pub fn chrome_for(style: TitleBarStyle, platform: Platform) -> WindowChrome {
    let overlay = matches!(style, TitleBarStyle::Overlay) && matches!(platform, Platform::Macos);
    WindowChrome {
        title_bar: if overlay { TitleBar::Overlay } else { TitleBar::Native },
    }
}

/// The calling window's declared style, from the generated config the shell was built with. A
/// window absent from the config (none today — `main` and `boot-error` are both declared) falls
/// back to tauri's own default, `Visible`, i.e. native.
fn declared_style(app: &tauri::AppHandle, label: &str) -> TitleBarStyle {
    app.config()
        .app
        .windows
        .iter()
        .find(|w| w.label == label)
        .map(|w| w.title_bar_style)
        .unwrap_or_default()
}

#[tauri::command]
#[specta::specta]
pub fn window_chrome(app: tauri::AppHandle, window: tauri::Window) -> WindowChrome {
    chrome_for(declared_style(&app, window.label()), current_platform())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::system_preconditions::Platform;
    use tauri::utils::TitleBarStyle;

    /// The ONE configuration where the OS overlays its controls on the webview: the window declares
    /// `Overlay` AND the host is macOS, the only OS where tauri honours that style.
    #[test]
    fn overlay_on_macos_is_the_only_overlay() {
        assert_eq!(chrome_for(TitleBarStyle::Overlay, Platform::Macos), WindowChrome { title_bar: TitleBar::Overlay });
    }

    /// Same declared style, other hosts: tauri falls back to the native decorated title bar, and the
    /// console must NOT reserve a band for controls that are drawn ABOVE it, not over it. `Platform`
    /// is a closed set — every non-mac variant is proven, no invented "freebsd" needed.
    #[test]
    fn overlay_elsewhere_is_native() {
        for platform in [Platform::Windows, Platform::Linux] {
            assert_eq!(chrome_for(TitleBarStyle::Overlay, platform), WindowChrome { title_bar: TitleBar::Native }, "{platform:?}");
        }
    }

    /// A window that never asked for Overlay (the boot-error splash; or config/window.ts flipped to
    /// Visible one day) is native even on macOS — the declared style is the fact, the OS only gates it.
    #[test]
    fn visible_and_transparent_are_native_even_on_macos() {
        assert_eq!(chrome_for(TitleBarStyle::Visible, Platform::Macos).title_bar, TitleBar::Native);
        assert_eq!(chrome_for(TitleBarStyle::Transparent, Platform::Macos).title_bar, TitleBar::Native);
    }

    /// The wire shape the react port declares BY HAND (`WindowService.ts`: `{ titleBar: 'overlay' |
    /// 'native' }`) — pinned here so a serde rename on this side fails in `cargo test`, not in the
    /// console at runtime.
    #[test]
    fn the_payload_is_camel_case_with_lowercase_variants() {
        let json = serde_json::to_value(WindowChrome { title_bar: TitleBar::Overlay }).expect("serialize");
        assert_eq!(json, serde_json::json!({ "titleBar": "overlay" }));
        let json = serde_json::to_value(WindowChrome { title_bar: TitleBar::Native }).expect("serialize");
        assert_eq!(json, serde_json::json!({ "titleBar": "native" }));
    }
}
