/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as appSuggestionsIndexRouteImport } from './routes/(app)/suggestions/index'
import { Route as appProductsIndexRouteImport } from './routes/(app)/products/index'
import { Route as appOrdersIndexRouteImport } from './routes/(app)/orders/index'
import { Route as appKanbanIndexRouteImport } from './routes/(app)/kanban/index'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appToolsCalculatorIndexRouteImport } from './routes/(app)/tools/calculator/index'
import { Route as appSettingsTaxesAndFeesIndexRouteImport } from './routes/(app)/settings/taxesAndFees/index'
import { Route as appSettingsIntegrationsIndexRouteImport } from './routes/(app)/settings/integrations/index'
import { Route as appSettingsAccountIndexRouteImport } from './routes/(app)/settings/account/index'
import { Route as appProductsKitsIndexRouteImport } from './routes/(app)/products/kits/index'
import { Route as appProductsCostsIndexRouteImport } from './routes/(app)/products/costs/index'
import { Route as appMarketingTrafficIndexRouteImport } from './routes/(app)/marketing/traffic/index'
import { Route as appKanbanBoardIdIndexRouteImport } from './routes/(app)/kanban/$boardId/index'
import { Route as appFinanceCostsIndexRouteImport } from './routes/(app)/finance/costs/index'
import { Route as appProductsCostsProductIdIndexRouteImport } from './routes/(app)/products/costs/$productId/index'
import { Route as appMarketingAccountsPlatformIndexRouteImport } from './routes/(app)/marketing/accounts/$platform/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSuggestionsIndexRoute = appSuggestionsIndexRouteImport.update({
  id: '/suggestions/',
  path: '/suggestions/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProductsIndexRoute = appProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrdersIndexRoute = appOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => appRouteRoute,
} as any)
const appKanbanIndexRoute = appKanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => appRouteRoute,
} as any)
const appToolsCalculatorIndexRoute = appToolsCalculatorIndexRouteImport.update({
  id: '/tools/calculator/',
  path: '/tools/calculator/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsTaxesAndFeesIndexRoute =
  appSettingsTaxesAndFeesIndexRouteImport.update({
    id: '/settings/taxesAndFees/',
    path: '/settings/taxesAndFees/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsIntegrationsIndexRoute =
  appSettingsIntegrationsIndexRouteImport.update({
    id: '/settings/integrations/',
    path: '/settings/integrations/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsAccountIndexRoute = appSettingsAccountIndexRouteImport.update({
  id: '/settings/account/',
  path: '/settings/account/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProductsKitsIndexRoute = appProductsKitsIndexRouteImport.update({
  id: '/products/kits/',
  path: '/products/kits/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProductsCostsIndexRoute = appProductsCostsIndexRouteImport.update({
  id: '/products/costs/',
  path: '/products/costs/',
  getParentRoute: () => appRouteRoute,
} as any)
const appMarketingTrafficIndexRoute =
  appMarketingTrafficIndexRouteImport.update({
    id: '/marketing/traffic/',
    path: '/marketing/traffic/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appKanbanBoardIdIndexRoute = appKanbanBoardIdIndexRouteImport.update({
  id: '/kanban/$boardId/',
  path: '/kanban/$boardId/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFinanceCostsIndexRoute = appFinanceCostsIndexRouteImport.update({
  id: '/finance/costs/',
  path: '/finance/costs/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProductsCostsProductIdIndexRoute =
  appProductsCostsProductIdIndexRouteImport.update({
    id: '/products/costs/$productId/',
    path: '/products/costs/$productId/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appMarketingAccountsPlatformIndexRoute =
  appMarketingAccountsPlatformIndexRouteImport.update({
    id: '/marketing/accounts/$platform/',
    path: '/marketing/accounts/$platform/',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/kanban/': typeof appKanbanIndexRoute
  '/orders/': typeof appOrdersIndexRoute
  '/products/': typeof appProductsIndexRoute
  '/suggestions/': typeof appSuggestionsIndexRoute
  '/finance/costs/': typeof appFinanceCostsIndexRoute
  '/kanban/$boardId/': typeof appKanbanBoardIdIndexRoute
  '/marketing/traffic/': typeof appMarketingTrafficIndexRoute
  '/products/costs/': typeof appProductsCostsIndexRoute
  '/products/kits/': typeof appProductsKitsIndexRoute
  '/settings/account/': typeof appSettingsAccountIndexRoute
  '/settings/integrations/': typeof appSettingsIntegrationsIndexRoute
  '/settings/taxesAndFees/': typeof appSettingsTaxesAndFeesIndexRoute
  '/tools/calculator/': typeof appToolsCalculatorIndexRoute
  '/marketing/accounts/$platform/': typeof appMarketingAccountsPlatformIndexRoute
  '/products/costs/$productId/': typeof appProductsCostsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/kanban': typeof appKanbanIndexRoute
  '/orders': typeof appOrdersIndexRoute
  '/products': typeof appProductsIndexRoute
  '/suggestions': typeof appSuggestionsIndexRoute
  '/finance/costs': typeof appFinanceCostsIndexRoute
  '/kanban/$boardId': typeof appKanbanBoardIdIndexRoute
  '/marketing/traffic': typeof appMarketingTrafficIndexRoute
  '/products/costs': typeof appProductsCostsIndexRoute
  '/products/kits': typeof appProductsKitsIndexRoute
  '/settings/account': typeof appSettingsAccountIndexRoute
  '/settings/integrations': typeof appSettingsIntegrationsIndexRoute
  '/settings/taxesAndFees': typeof appSettingsTaxesAndFeesIndexRoute
  '/tools/calculator': typeof appToolsCalculatorIndexRoute
  '/marketing/accounts/$platform': typeof appMarketingAccountsPlatformIndexRoute
  '/products/costs/$productId': typeof appProductsCostsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/kanban/': typeof appKanbanIndexRoute
  '/(app)/orders/': typeof appOrdersIndexRoute
  '/(app)/products/': typeof appProductsIndexRoute
  '/(app)/suggestions/': typeof appSuggestionsIndexRoute
  '/(app)/finance/costs/': typeof appFinanceCostsIndexRoute
  '/(app)/kanban/$boardId/': typeof appKanbanBoardIdIndexRoute
  '/(app)/marketing/traffic/': typeof appMarketingTrafficIndexRoute
  '/(app)/products/costs/': typeof appProductsCostsIndexRoute
  '/(app)/products/kits/': typeof appProductsKitsIndexRoute
  '/(app)/settings/account/': typeof appSettingsAccountIndexRoute
  '/(app)/settings/integrations/': typeof appSettingsIntegrationsIndexRoute
  '/(app)/settings/taxesAndFees/': typeof appSettingsTaxesAndFeesIndexRoute
  '/(app)/tools/calculator/': typeof appToolsCalculatorIndexRoute
  '/(app)/marketing/accounts/$platform/': typeof appMarketingAccountsPlatformIndexRoute
  '/(app)/products/costs/$productId/': typeof appProductsCostsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password/'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/'
    | '/kanban/'
    | '/orders/'
    | '/products/'
    | '/suggestions/'
    | '/finance/costs/'
    | '/kanban/$boardId/'
    | '/marketing/traffic/'
    | '/products/costs/'
    | '/products/kits/'
    | '/settings/account/'
    | '/settings/integrations/'
    | '/settings/taxesAndFees/'
    | '/tools/calculator/'
    | '/marketing/accounts/$platform/'
    | '/products/costs/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/kanban'
    | '/orders'
    | '/products'
    | '/suggestions'
    | '/finance/costs'
    | '/kanban/$boardId'
    | '/marketing/traffic'
    | '/products/costs'
    | '/products/kits'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/taxesAndFees'
    | '/tools/calculator'
    | '/marketing/accounts/$platform'
    | '/products/costs/$productId'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/reset-password/'
    | '/sign-in/'
    | '/sign-up/'
    | '/(app)/dashboard/'
    | '/(app)/kanban/'
    | '/(app)/orders/'
    | '/(app)/products/'
    | '/(app)/suggestions/'
    | '/(app)/finance/costs/'
    | '/(app)/kanban/$boardId/'
    | '/(app)/marketing/traffic/'
    | '/(app)/products/costs/'
    | '/(app)/products/kits/'
    | '/(app)/settings/account/'
    | '/(app)/settings/integrations/'
    | '/(app)/settings/taxesAndFees/'
    | '/(app)/tools/calculator/'
    | '/(app)/marketing/accounts/$platform/'
    | '/(app)/products/costs/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/suggestions/': {
      id: '/(app)/suggestions/'
      path: '/suggestions'
      fullPath: '/suggestions/'
      preLoaderRoute: typeof appSuggestionsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/products/': {
      id: '/(app)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof appProductsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/orders/': {
      id: '/(app)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof appOrdersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/kanban/': {
      id: '/(app)/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof appKanbanIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tools/calculator/': {
      id: '/(app)/tools/calculator/'
      path: '/tools/calculator'
      fullPath: '/tools/calculator/'
      preLoaderRoute: typeof appToolsCalculatorIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/taxesAndFees/': {
      id: '/(app)/settings/taxesAndFees/'
      path: '/settings/taxesAndFees'
      fullPath: '/settings/taxesAndFees/'
      preLoaderRoute: typeof appSettingsTaxesAndFeesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/integrations/': {
      id: '/(app)/settings/integrations/'
      path: '/settings/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof appSettingsIntegrationsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/account/': {
      id: '/(app)/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof appSettingsAccountIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/products/kits/': {
      id: '/(app)/products/kits/'
      path: '/products/kits'
      fullPath: '/products/kits/'
      preLoaderRoute: typeof appProductsKitsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/products/costs/': {
      id: '/(app)/products/costs/'
      path: '/products/costs'
      fullPath: '/products/costs/'
      preLoaderRoute: typeof appProductsCostsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/marketing/traffic/': {
      id: '/(app)/marketing/traffic/'
      path: '/marketing/traffic'
      fullPath: '/marketing/traffic/'
      preLoaderRoute: typeof appMarketingTrafficIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/kanban/$boardId/': {
      id: '/(app)/kanban/$boardId/'
      path: '/kanban/$boardId'
      fullPath: '/kanban/$boardId/'
      preLoaderRoute: typeof appKanbanBoardIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/finance/costs/': {
      id: '/(app)/finance/costs/'
      path: '/finance/costs'
      fullPath: '/finance/costs/'
      preLoaderRoute: typeof appFinanceCostsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/products/costs/$productId/': {
      id: '/(app)/products/costs/$productId/'
      path: '/products/costs/$productId'
      fullPath: '/products/costs/$productId/'
      preLoaderRoute: typeof appProductsCostsProductIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/marketing/accounts/$platform/': {
      id: '/(app)/marketing/accounts/$platform/'
      path: '/marketing/accounts/$platform'
      fullPath: '/marketing/accounts/$platform/'
      preLoaderRoute: typeof appMarketingAccountsPlatformIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appKanbanIndexRoute: typeof appKanbanIndexRoute
  appOrdersIndexRoute: typeof appOrdersIndexRoute
  appProductsIndexRoute: typeof appProductsIndexRoute
  appSuggestionsIndexRoute: typeof appSuggestionsIndexRoute
  appFinanceCostsIndexRoute: typeof appFinanceCostsIndexRoute
  appKanbanBoardIdIndexRoute: typeof appKanbanBoardIdIndexRoute
  appMarketingTrafficIndexRoute: typeof appMarketingTrafficIndexRoute
  appProductsCostsIndexRoute: typeof appProductsCostsIndexRoute
  appProductsKitsIndexRoute: typeof appProductsKitsIndexRoute
  appSettingsAccountIndexRoute: typeof appSettingsAccountIndexRoute
  appSettingsIntegrationsIndexRoute: typeof appSettingsIntegrationsIndexRoute
  appSettingsTaxesAndFeesIndexRoute: typeof appSettingsTaxesAndFeesIndexRoute
  appToolsCalculatorIndexRoute: typeof appToolsCalculatorIndexRoute
  appMarketingAccountsPlatformIndexRoute: typeof appMarketingAccountsPlatformIndexRoute
  appProductsCostsProductIdIndexRoute: typeof appProductsCostsProductIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardIndexRoute: appDashboardIndexRoute,
  appKanbanIndexRoute: appKanbanIndexRoute,
  appOrdersIndexRoute: appOrdersIndexRoute,
  appProductsIndexRoute: appProductsIndexRoute,
  appSuggestionsIndexRoute: appSuggestionsIndexRoute,
  appFinanceCostsIndexRoute: appFinanceCostsIndexRoute,
  appKanbanBoardIdIndexRoute: appKanbanBoardIdIndexRoute,
  appMarketingTrafficIndexRoute: appMarketingTrafficIndexRoute,
  appProductsCostsIndexRoute: appProductsCostsIndexRoute,
  appProductsKitsIndexRoute: appProductsKitsIndexRoute,
  appSettingsAccountIndexRoute: appSettingsAccountIndexRoute,
  appSettingsIntegrationsIndexRoute: appSettingsIntegrationsIndexRoute,
  appSettingsTaxesAndFeesIndexRoute: appSettingsTaxesAndFeesIndexRoute,
  appToolsCalculatorIndexRoute: appToolsCalculatorIndexRoute,
  appMarketingAccountsPlatformIndexRoute:
    appMarketingAccountsPlatformIndexRoute,
  appProductsCostsProductIdIndexRoute: appProductsCostsProductIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
