import { injectable } from 'tsyringe-neo'
import { Controller, MimeTypes, z, BaseError } from '@codedm/core-typescript'
import type { HttpMethod } from '@codedm/core-typescript'
import { withMcpRunContext, MCP_RUN_TOKEN_HEADER } from '@codedm/client-typescript/mcp-run-context'
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js'
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { RunTokenService, type RunTokenClaims } from '../services/RunTokenService'
import { MCP_SCOPE_NAMES, type McpScope } from './manifest'
import { assertIdentityMatchesClaims } from './identity'
import type { AgentInterfaceErrors } from '../errors'

import { MCP_ROUTE_PREFIX } from './route'

export { MCP_ROUTE_PREFIX }

const McpRouterInputSchema = z.object({ params: z.object({ scope: z.string() }) })
const McpRouterOutputSchema = z.any()

/** JSON-RPC 2.0 error codes we produce ourselves, before the transport ever sees the message. */
const JSONRPC_INVALID_PARAMS = -32602

/**
 * THE MCP DOOR — the JSON-RPC endpoint an agent CLI talks to, and the place the mandatory identity
 * mitigation lives (GOAL-agent-abstraction §4.4, AC-6.6/AC-6.12/AC-6.16).
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────────
 * IT IS A REAL ROUTE THAT IS DELIBERATELY NOT IN THE SPEC
 * Mounted only when `EMIT_OPENAPI !== 'true'` (see `agent/index.ts`), exactly like `ChannelProxy` and
 * `TestIngressController`. A JSON-RPC tool endpoint rendered into the SDK would become React Query
 * hooks with no consumer — noise in the surface the console imports. "Not emitted" is not "not
 * mounted", which is why AC-6.8(d) pairs the grep with an actual `initialize` round trip.
 *
 * THE TOOLS ARE GENERATED, SO THIS FILE REGISTERS NOTHING
 * `getServer()` comes from `@kubb/plugin-mcp` output, built from the same OpenAPI that builds the SDK.
 * There is no hand-written tool, no hand-written tool schema, and no second mechanism: a tool IS a
 * controller, reached over HTTP, dispatching a use case (AC-6.18). The generated `startServer()` is
 * deliberately unused — it hardcodes stdio; we bind the transport ourselves.
 *
 * AUTHORIZATION IS PER CALL, NOT PER RUN
 * Every request carries the opaque run token. `verify` is a map lookup that fails closed on unknown,
 * expired and revoked, so a late tool call from a run that already died gets 401 and writes nothing —
 * the property §4.11 promises when a run is cancelled.
 *
 * IDENTITY IS CHECKED BEFORE THE TRANSPORT DISPATCHES, WHICH IS WHY "NO WRITE HAPPENED" IS PROVABLE
 * The message is parsed here, and a `tools/call` has its arguments walked against the claims BEFORE
 * `handleRequest` runs. Doing it inside a tool wrapper would be too late in a measurable way: the MCP
 * SDK validates `outputSchema` AFTER the handler returns, and the probe caught a rejected call whose
 * HTTP write had already been issued. Rejecting here means the outbound request is never built.
 * ─────────────────────────────────────────────────────────────────────────────────────────────────
 */
@injectable()
export class McpRouterController extends Controller<typeof McpRouterInputSchema, typeof McpRouterOutputSchema> {
	readonly path = `${MCP_ROUTE_PREFIX}/:scope` as const
	readonly method: HttpMethod[] = ['post', 'get', 'delete']
	readonly description = 'CodeDM MCP server (JSON-RPC) — not emitted to the OpenAPI/SDK'
	readonly inputSchema = McpRouterInputSchema
	readonly outputSchema = McpRouterOutputSchema
	override readonly contentType: MimeTypes = MimeTypes['.stream']

	// NO middlewares. `OperatorMiddleware` would stamp the daemon's own operator identity onto every
	// call unconditionally — the confused-deputy shape this whole file exists to prevent. Authority
	// here comes from the run token and from nothing else.
	override middlewares = []

	/**
	 * One `McpServer` + transport per scope, built lazily on first use and then reused.
	 *
	 * Lazy because the generated module is imported dynamically (it lives in the SDK package, which is
	 * regenerated by `bun sdk`; a static import would make this file's module graph depend on codegen
	 * output at load time). Reused because `getServer()` constructs a fresh `McpServer` per call and a
	 * per-request server would re-register every tool on every message.
	 */
	private readonly servers = new Map<McpScope, Promise<WebStandardStreamableHTTPServerTransport>>()

	constructor(private readonly runTokens: RunTokenService) {
		super()
	}

	async handle(request: this['input']): Promise<this['output']> {
		const scope = this.resolveScope(request.params.scope)
		const raw = request.raw
		const token = this.readToken(raw)
		const claims = this.runTokens.verify(token)
		if (!claims) {
			throw new BaseError<AgentInterfaceErrors>('AGENT_RUN_TOKEN_INVALID', 'missing, unknown, expired or revoked run token')
		}

		// The body is consumed here to inspect it, so the transport is handed a fresh Request built
		// from the bytes we already read — a Request body is a one-shot stream and re-reading it would
		// hand the transport an empty message.
		const body = raw.method === 'POST' ? await raw.text() : ''
		const identityError = this.rejectMismatchedIdentity(body, claims)
		if (identityError) return this.rawResponse(identityError)

		const transport = await this.transportFor(scope)
		const replay = new Request(raw.url, {
			method: raw.method,
			headers: raw.headers,
			...(body.length > 0 && { body }),
		})

		// The context the generated `_http.ts` shims read to attach the token to their outbound call.
		// Established AROUND the whole dispatch, so it covers every async continuation the transport
		// spawns — a per-tool wrapper would miss the ones the SDK schedules itself.
		return this.rawResponse(await withMcpRunContext({ token }, () => transport.handleRequest(replay)))
	}

	/**
	 * A scope that is not in the manifest is not a typo to be guessed at — it is a request for a tool
	 * surface that was never declared, and answering it with the wrong scope's tools would be exactly
	 * the accidental exposure the allowlist exists to prevent.
	 */
	private resolveScope(candidate: string): McpScope {
		const scope = MCP_SCOPE_NAMES.find(name => name === candidate)
		if (!scope) throw new BaseError<AgentInterfaceErrors>('AGENT_RUN_TOKEN_INVALID', `unknown MCP scope '${candidate}'`)
		return scope
	}

	/** `Authorization: Bearer <token>` or the dedicated header — CLIs differ on which they can set. */
	private readToken(raw: Request): string {
		const dedicated = raw.headers.get(MCP_RUN_TOKEN_HEADER)
		if (dedicated) return dedicated
		const authorization = raw.headers.get('authorization') ?? ''
		return authorization.toLowerCase().startsWith('bearer ') ? authorization.slice('bearer '.length).trim() : ''
	}

	/**
	 * Walk a `tools/call`'s arguments against the claims and, on disagreement, answer with a JSON-RPC
	 * error INSTEAD of dispatching. Returns `null` when there is nothing to reject.
	 *
	 * A JSON-RPC error object rather than a thrown `BaseError`: the caller is an MCP client, and an
	 * HTTP 403 with our error envelope would arrive at the model as a transport failure it cannot
	 * interpret. The code is echoed in the message so the log and the client agree on WHY, and the
	 * status stays 200 because the JSON-RPC layer, not HTTP, is where this conversation's errors live.
	 *
	 * A message that does not parse is passed through untouched — the transport owns malformed-input
	 * handling, and duplicating its error vocabulary here would be a second source of truth for it.
	 */
	private rejectMismatchedIdentity(body: string, claims: RunTokenClaims): Response | null {
		if (body.length === 0) return null
		let message: unknown
		try {
			message = JSON.parse(body)
		} catch {
			return null
		}

		for (const call of this.toolCallsIn(message)) {
			try {
				assertIdentityMatchesClaims(call.args, claims)
			} catch (error) {
				const detail = error instanceof BaseError ? error.message : String(error)
				return Response.json(
					{
						jsonrpc: '2.0',
						id: call.id ?? null,
						error: { code: JSONRPC_INVALID_PARAMS, message: `AGENT_RUN_SCOPE_MISMATCH: ${detail}` },
					},
					{ status: 200 },
				)
			}
		}
		return null
	}

	/** Every `tools/call` in the message — JSON-RPC allows a BATCH, and one bad member taints the batch. */
	private toolCallsIn(message: unknown): Array<{ id: unknown; args: unknown }> {
		const messages = Array.isArray(message) ? message : [message]
		const calls: Array<{ id: unknown; args: unknown }> = []
		for (const entry of messages) {
			if (!entry || typeof entry !== 'object') continue
			const record = entry as { method?: unknown; id?: unknown; params?: { arguments?: unknown } }
			if (record.method !== 'tools/call') continue
			calls.push({ id: record.id, args: record.params?.arguments })
		}
		return calls
	}

	private transportFor(scope: McpScope): Promise<WebStandardStreamableHTTPServerTransport> {
		const existing = this.servers.get(scope)
		if (existing) return existing
		const created = this.buildTransport(scope)
		this.servers.set(scope, created)
		return created
	}

	private async buildTransport(scope: McpScope): Promise<WebStandardStreamableHTTPServerTransport> {
		const server = await loadGeneratedServer(scope)
		// Stateless: `sessionIdGenerator: undefined` makes every POST self-contained. An agent CLI
		// spawns per turn and never resumes an MCP session, so session state would only be a table of
		// entries nothing ever reads — and one more thing to leak when a run is killed.
		const transport = new WebStandardStreamableHTTPServerTransport({ sessionIdGenerator: undefined, enableJsonResponse: true })
		await server.connect(transport)
		return transport
	}
}

/**
 * Import the generated per-scope server. Isolated in a function so the dynamic specifier appears once,
 * and so a test can assert the emitted module actually LOADS — `tsc` resolving it proves nothing about
 * runtime, which is the whole lesson of AC-6.16 (the generator emits extensionless
 * `@modelcontextprotocol/sdk/server/mcp` imports that typecheck and then fail to resolve at runtime;
 * our generator rewrites them, and only a runtime smoke can tell you it worked).
 */
export async function loadGeneratedServer(scope: McpScope): Promise<McpServer> {
	const module = (await import(`@codedm/client-typescript/typescript/mcp-${scope}/server`)) as { getServer: () => McpServer }
	return module.getServer()
}
