//! Build script — tauri's own codegen PLUS the shell env contract.
//!
//! `shell-env.json` (generated by `bun desktop:generate` from `config/env.ts`, committed, drift-gated)
//! lists, per sidecar role, the env the shell supplies at boot: the keys `template.config.ts`
//! declares the shell reads. Each pair becomes `cargo:rustc-env=CODM_SHELL_ENV_<ROLE>_<KEY>=<value>`,
//! and `src/shell_env.rs` reads them back with `env!()` — compile-time constants, so a missing key
//! is a COMPILE error, never a daemon that boots without knowing where the cloud lives (0.5.1).
//!
//! A value is either a single string (a URL, a brand name) or a JSON ARRAY of strings — the
//! PACKAGED app's candidate ports (spec 2026-08-25/26: a single hardcoded port collided with an
//! unrelated dev server on the same machine). An array is joined with `,` into ONE emitted env var
//! (`env!()` only ever reads a string); `src/shell_env.rs::port_candidates` splits it back. Which
//! shape a key carries is read off the JSON VALUE itself (`serde_json::Value::Array` vs `::String`),
//! never off a naming convention on the key.
//!
//! Validation happens here, once, at the edge: a port must parse as `u16`, a URL must be absolute.
//! The runtime readers trust that and only parse.

use std::collections::BTreeMap;
use std::path::Path;

const SHELL_ENV_FILE: &str = "shell-env.json";

fn main() {
    emit_shell_env();
    declare_common_controls_dependency();
    tauri_build::build()
}

/// O MANIFESTO QUE O BINARIO DE TESTE NAO GANHAVA — e sem o qual `cargo test` nem chegava a rodar.
///
/// Este crate importa `TaskDialogIndirect`, `SetWindowSubclass`, `RemoveWindowSubclass` e
/// `DefSubclassProc` (via a arvore do Tauri). As quatro existem SOMENTE no comctl32 **v6**, que no
/// Windows e um assembly side-by-side: um processo so o recebe se declarar a dependencia num
/// manifesto. Sem isso o carregador entrega o comctl32 v5 do System32 — medido: ZERO ocorrencias de
/// `TaskDialogIndirect` nos exports dele — e o processo morre ANTES do `main` com
/// `STATUS_ENTRYPOINT_NOT_FOUND` (0xc0000139), sem uma linha de teste executada e sem nomear a
/// funcao que faltou.
///
/// O binario do APP ja tinha manifesto (`tauri_build::build()` embute um pelo `.rc`), e o binario de
/// teste do BIN herda o mesmo recurso — medido: os dois carregam a string `Common-Controls`. Só o
/// binario de teste da LIB nao carregava nenhum. A diferenca nunca esteve no codigo: esteve em qual
/// binario recebia o recurso.
///
/// ── POR QUE UM MANIFESTO EXTERNO, E NAO `/MANIFEST:EMBED` ───────────────────────────────────────
/// Duas tentativas foram descartadas por medicao, e vale registrar as duas:
///
///  1. `cargo:rustc-link-arg-tests` NAO alcanca o teste unitario da lib — ele cobre os alvos
///     `[[test]]`, e o binario de teste da lib e o alvo `lib` compilado com `--test`. As diretivas
///     saiam no output do build script e o binario continuava sem manifesto.
///  2. `cargo:rustc-link-arg=/MANIFEST:EMBED` alcanca tudo — e QUEBRA o bin, que ja tem um manifesto
///     embutido pelo Tauri: `LINK : fatal error LNK1123: falha durante conversao para COFF`.
///
/// Sobra `/MANIFESTDEPENDENCY` sozinho. Com o `/MANIFEST` que o linker ja usa por padrao, ele grava
/// um `<binario>.manifest` AO LADO do executavel — que e exatamente onde o carregador do Windows
/// procura quando nao ha manifesto embutido. Para o bin e para o app nada muda: um manifesto
/// EMBUTIDO tem precedencia sobre o externo, entao o do Tauri continua sendo o que vale, e o arquivo
/// gerado ao lado e inerte. Para o teste da lib, que nao tinha nenhum, o externo passa a ser o
/// manifesto — e os 86 testes voltam a rodar.
///
/// O recorte por `CARGO_CFG_TARGET_ENV == "msvc"` nao e um desvio sobre convencao: `/MANIFEST*` sao
/// flags do linker da MSVC e so existem nesse alvo. No mac e no Linux esta funcao nao emite nada,
/// nao ha comctl32, e `cargo test` de la nunca teve este problema.
fn declare_common_controls_dependency() {
    if std::env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("msvc") {
        return;
    }
    println!(
        "cargo:rustc-link-arg=/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"
    );
}

fn emit_shell_env() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(SHELL_ENV_FILE);
    println!("cargo:rerun-if-changed={}", path.display());

    let raw = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "{SHELL_ENV_FILE} missing at {} ({err}) — it is generated: run `bun desktop:generate` at the repo root",
            path.display()
        )
    });
    // BTreeMap: deterministic emission order, so two builds of the same JSON print the same lines.
    // `serde_json::Value` for the leaf because a leaf is EITHER a string OR an array of strings —
    // see the module doc.
    let by_role: BTreeMap<String, BTreeMap<String, serde_json::Value>> = serde_json::from_str(&raw).unwrap_or_else(|err| {
        panic!("{SHELL_ENV_FILE} is not `{{ role: {{ KEY: value | value[] }} }}` ({err}) — regenerate with `bun desktop:generate`")
    });

    let mut emitted = 0usize;
    for (role, env) in &by_role {
        for (key, value) in env {
            let joined = match value {
                serde_json::Value::String(s) => {
                    validate(role, key, s);
                    s.clone()
                }
                serde_json::Value::Array(items) => {
                    let strs: Vec<String> = items
                        .iter()
                        .map(|item| {
                            item.as_str().unwrap_or_else(|| {
                                panic!("{SHELL_ENV_FILE}: {role}.{key} candidate {item:?} is not a string")
                            })
                        })
                        .map(|s| {
                            validate(role, key, s);
                            s.to_owned()
                        })
                        .collect();
                    assert!(!strs.is_empty(), "{SHELL_ENV_FILE}: {role}.{key} is an empty candidate list");
                    // `,` is safe as a joiner: `validate` below already refuses any value containing
                    // one (ports and URLs never legitimately do).
                    strs.join(",")
                }
                other => panic!("{SHELL_ENV_FILE}: {role}.{key} = {other:?} is neither a string nor an array of strings"),
            };
            println!(
                "cargo:rustc-env=CODM_SHELL_ENV_{}_{}={}",
                role.to_ascii_uppercase(),
                key.to_ascii_uppercase(),
                joined
            );
            emitted += 1;
        }
    }
    assert!(emitted > 0, "{SHELL_ENV_FILE} declares no env at all — the manifest lost every `appTauri` consumer?");
}

/// The value class is named by the KEY, the same convention the manifest's examples follow:
/// `*_PORT` is a port, `*_URL` is an absolute http(s) origin. Anything else passes through. Runs on
/// every element of a candidate list too (called once per string either way).
fn validate(role: &str, key: &str, value: &str) {
    if key.ends_with("_PORT") {
        assert!(
            value.parse::<u16>().is_ok(),
            "{SHELL_ENV_FILE}: {role}.{key} = {value:?} is not a port"
        );
    } else if key.ends_with("_URL") {
        assert!(
            value.starts_with("http://") || value.starts_with("https://"),
            "{SHELL_ENV_FILE}: {role}.{key} = {value:?} is not an absolute http(s) URL"
        );
    }
    assert!(!value.contains('\n'), "{SHELL_ENV_FILE}: {role}.{key} contains a newline");
    assert!(!value.contains(','), "{SHELL_ENV_FILE}: {role}.{key} = {value:?} contains a comma — it is the candidate-list joiner");
}
