/**
 * Error-code union generator — renders the backends' REGISTERED error vocabulary into the SDK.
 *
 * Source of truth: each service's openapi.json root `x-error-codes` (emitted by the api's
 * OpenAPI generator from the runtime GlobalErrorMapper — core seed + every context's
 * registerErrorCodes). The union of all services lands in
 * `dist/typescript/src/error-codes/index.ts`, importable as
 * `@codedm/client-typescript/error-codes` (the dist wildcard subpath export).
 *
 * Consumers: app locale catalogues compile-check their `errors` section with
 * `satisfies Record<ErrorCode, string>` — a backend code without a translation is a tsc
 * error, not a runtime raw-key render (user decision: the error-enum × i18n contract is
 * compile-time). Runs AFTER kubb (which wipes dist src) in the client `generate` chain.
 */
import path from 'node:path'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { discoverApis } from '../lib/discover'

const repoRoot = path.resolve(import.meta.dirname, '../../..')
const outDir = path.resolve(import.meta.dirname, '../dist/typescript/src/error-codes')

async function main(): Promise<void> {
	const sources = await discoverApis(repoRoot)
	const codes = new Set<string>()
	let carriers = 0
	for (const source of sources) {
		const spec = JSON.parse(await readFile(source.specPath, 'utf8')) as { 'x-error-codes'?: string[] }
		const list = spec['x-error-codes']
		if (!Array.isArray(list)) continue
		carriers++
		for (const code of list) codes.add(code)
	}
	if (carriers === 0 || codes.size === 0) {
		throw new Error(
			'error-codes: no discovered openapi.json carries x-error-codes — the api emitter ' +
				'(core OpenAPI.generateSpecification) and this generator drifted. Regenerate the specs first (bun emit-openapi).',
		)
	}

	const sorted = [...codes].sort()
	const body = `// GENERATED by packages/client/generators/error-codes.ts — do not edit.
// The backends' full registered error-code vocabulary (openapi.json x-error-codes union).
export const ERROR_CODES = [
${sorted.map(c => `\t'${c}',`).join('\n')}
] as const

export type ErrorCode = (typeof ERROR_CODES)[number]
`
	await mkdir(outDir, { recursive: true })
	await writeFile(path.join(outDir, 'index.ts'), body)
	console.log(`[error-codes] ${sorted.length} codes from ${carriers} service spec(s) → dist/typescript/src/error-codes/index.ts`)
}

await main()
