/**
 * Go client generator — wraps `go tool oapi-codegen` per discovered service,
 * then renders the aggregate `pkg/client/client.go`.
 */
import path from 'node:path'
import fs from 'node:fs'
import os from 'node:os'
import { writeFile, mkdir } from 'node:fs/promises'
import { discoverApis, type ApiSource } from '../lib/discover'
import { assertClientDistRoot } from '../lib/output-root'
import { preprocessSpec } from '../lib/preprocess'
import { renderAggregateClientGo, type ServiceMeta } from '../lib/render/go'
import { goPackageIdent } from '../lib/sanitize'

const repoRoot = path.resolve(import.meta.dir, '../../..')
const distRoot = assertClientDistRoot(path.resolve(import.meta.dir, '../dist/go'))

interface Plan {
	source: ApiSource
	preprocessedSpecPath: string
	outDir: string
	pkg: string
	hasPaths: boolean
}

async function preprocessAll(sources: ApiSource[]): Promise<Plan[]> {
	const plans: Plan[] = []
	for (const source of sources) {
		const { spec } = await preprocessSpec(source.specPath)
		const tmp = path.join(os.tmpdir(), `client-go-${source.service}.openapi.json`)
		await writeFile(tmp, JSON.stringify(spec))
		const hasPaths = Object.keys((spec.paths ?? {}) as object).length > 0
		plans.push({
			source,
			preprocessedSpecPath: tmp,
			outDir: path.join(distRoot, 'pkg', source.service),
			pkg: goPackageIdent(source.service),
			hasPaths,
		})
	}
	return plans
}

function writePlaceholder(plan: Plan): void {
	fs.mkdirSync(plan.outDir, { recursive: true })
	const out = path.join(plan.outDir, 'client.gen.go')
	fs.writeFileSync(out, `// Code generated by client generator — DO NOT EDIT.\npackage ${plan.pkg}\n`)
}

function writeOapiConfig(plan: Plan): string {
	const cfgPath = path.join(os.tmpdir(), `client-go-${plan.source.service}.yaml`)
	const outRel = path.relative(distRoot, path.join(plan.outDir, 'client.gen.go'))
	fs.writeFileSync(
		cfgPath,
		[
			`package: ${plan.pkg}`,
			`generate:`,
			`  models: true`,
			`  client: true`,
			`  std-http-server: false`,
			`  embedded-spec: false`,
			`output: ${outRel}`,
			`output-options:`,
			`  skip-prune: true`,
			`  nullable-type: true`,
			``,
		].join('\n'),
	)
	return cfgPath
}

async function runOapiCodegen(plan: Plan, configPath: string): Promise<void> {
	const proc = Bun.spawn(['go', 'tool', 'oapi-codegen', '--config', configPath, plan.preprocessedSpecPath], {
		cwd: distRoot,
		stdout: 'inherit',
		stderr: 'inherit',
	})
	const exit = await proc.exited
	if (exit !== 0) throw new Error(`[${plan.source.service}] oapi-codegen exited ${exit}`)
}

async function emitAggregate(plans: Plan[]): Promise<void> {
	const dir = path.join(distRoot, 'pkg', 'client')
	await mkdir(dir, { recursive: true })
	const metas: ServiceMeta[] = plans.filter(p => p.hasPaths).map(p => ({ source: p.source }))
	const code = renderAggregateClientGo(metas)
	await writeFile(path.join(dir, 'client.go'), code)
}

async function main(): Promise<void> {
	console.log('client-go generator')
	const sources = await discoverApis(repoRoot)
	if (sources.length === 0) {
		console.error('No api services discovered.')
		process.exit(1)
	}
	console.log('discovered:', sources.map(s => s.service).join(', '))

	const plans = await preprocessAll(sources)
	for (const plan of plans) {
		if (!plan.hasPaths) {
			writePlaceholder(plan)
			continue
		}
		fs.mkdirSync(plan.outDir, { recursive: true })
		const cfg = writeOapiConfig(plan)
		try {
			await runOapiCodegen(plan, cfg)
		} finally {
			try {
				fs.unlinkSync(cfg)
			} catch {}
		}
	}
	await emitAggregate(plans)
	console.log('done.')
}

main()
