// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async secretGet(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("secret_get", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async secretSet(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("secret_set", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async secretDelete(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("secret_delete", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bootFailures() : Promise<SidecarFailure[]> {
    return await TAURI_INVOKE("boot_failures");
},
/**
 * Retry = boot again. `restart()` and nothing else: the sidecar descriptors are derived in `setup`
 * (data dir, resource dir), and retaining them just to re-spawn would be inventing state to
 * reimplement — worse — what the process already does for free.
 */
async retryBoot() : Promise<void> {
    await TAURI_INVOKE("retry_boot");
},
async hostPorts() : Promise<HostPorts> {
    return await TAURI_INVOKE("host_ports");
},
async supervisionState() : Promise<SupervisionState> {
    return await TAURI_INVOKE("supervision_state");
},
async pendingUpdate() : Promise<string | null> {
    return await TAURI_INVOKE("pending_update");
},
/**
 * The operator's one action once `pending_update` (or the `UpdateReady` event) says a version is
 * ready: relaunch into the bits `run_check` already installed. Same primitive as `retry_boot` —
 * `handle.restart()` — behind a different trigger.
 */
async restartForUpdate() : Promise<void> {
    await TAURI_INVOKE("restart_for_update");
},
async systemPreconditionStatuses() : Promise<SystemPreconditionStatus[]> {
    return await TAURI_INVOKE("system_precondition_statuses");
},
/**
 * O bundle id NÃO é literal aqui: sai de `config().identifier`, o mesmo valor de onde `lib.rs`
 * deriva o data dir. `tccutil` apagando a entrada de outro app seria uma limpeza silenciosa que
 * não conserta nada e mexe onde não devia.
 */
async repairSystemPrecondition(id: SystemPreconditionId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_system_precondition", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async windowChrome() : Promise<WindowChrome> {
    return await TAURI_INVOKE("window_chrome");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
supervisionChanged: SupervisionChanged,
updateReady: UpdateReady
}>({
supervisionChanged: "supervision-changed",
updateReady: "update-ready"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * What crosses to the console. `api_port` is the one the react `Config` actually needs
 * (`serviceBaseUrls.typescript` / `.go` both resolve through the daemon — the browser never talks
 * to the gateway directly, see `packages/app/react/src/lib/config.ts`); `channel_port` rides along
 * for diagnostics/symmetry with what the shell resolved.
 */
export type HostPorts = { apiPort: number; channelPort: number }
/**
 * Se o reparo de uma pré-condição TEM efeito neste host — cruza `repair_scope` (declarado) com
 * `has_attributable_identity()` (derivado do processo). Um `AppGrant` sem identidade atribuível
 * não tem bundle para o `tccutil` limpar nem app para listar nos Ajustes.
 */
export type RepairAvailability = "AVAILABLE" | 
/**
 * O host não consegue atribuir a concessão a este app — quem a carrega é o processo
 * responsável (em `tauri dev`, o terminal).
 */
"NO_APP_IDENTITY"
/**
 * What a sidecar that never came up leaves for the operator to read.
 */
export type SidecarFailure = { name: string; 
/**
 * Why we gave up: the spawn failed, or no healthy answer within the budget.
 */
reason: string; 
/**
 * The retained tail of captured stderr, in chronological order.
 */
stderr: string[]; 
/**
 * Where the FULL stderr for this run was persisted (`sidecar_log::SidecarLog`), so the splash
 * can tell the operator where to look instead of only showing the 50-line tail above. `None`
 * when no process ever ran (port conflict, spawn setup failure) — there is nothing on disk to
 * point to — or when the write itself was best-effort-skipped.
 */
logPath: string | null }
/**
 * Which SDK sub-client answers for a sidecar — and, since supervision, which one the console is
 * being told about. A fact of the SHELL (which binary is which service), never a contract enum:
 * it crosses to the webview as the shell's own supervision payload (specta), not through
 * `packages/contracts` (spec Decision 10).
 */
export type SidecarService = "daemon" | "gateway"
/**
 * The transition, on its way to the console (PUSH half of spec Decision 9). Typed end-to-end by
 * tauri-specta exactly like the custom commands — the console gets
 * `events.supervisionChanged.listen(...)`, never a stringly `listen('supervision:changed')`.
 * 
 * The derive is TRANSPORT only: `SupervisionMonitor` above neither knows nor can reach it, which is
 * what keeps the machine testable without an app.
 */
export type SupervisionChanged = { state: SupervisionState }
/**
 * What the console is shown. `Degraded`/`Down` name WHICH sidecar, because the reaction differs by
 * sidecar (spec Decision 6): the daemon is the whole app, the gateway is the channel.
 */
export type SupervisionState = { kind: "healthy" } | { kind: "degraded"; sidecar: SidecarService } | { kind: "down"; sidecar: SidecarService }
/**
 * Os ids. Estável em toda plataforma — ver o doc do módulo.
 */
export type SystemPreconditionId = "FULL_DISK_ACCESS"
/**
 * O que atravessa para o console. Só os aplicáveis.
 */
export type SystemPreconditionStatus = { id: SystemPreconditionId; satisfied: boolean; repair: RepairAvailability }
/**
 * Who draws the window controls, from the webview's point of view.
 */
export type TitleBar = 
/**
 * The OS overlays its controls ON the webview (macOS `titleBarStyle: Overlay`): the console
 * owns the full window height and must reserve the traffic-light band.
 */
"overlay" | 
/**
 * The OS draws a decorated title bar ABOVE the webview (Windows, Linux — or any window that
 * did not ask for Overlay): nothing overlaps the console, nothing to reserve.
 */
"native"
/**
 * PUSH half — mirrors `SupervisionChanged`'s shape and purpose: typed end-to-end by tauri-specta,
 * so the console gets `events.updateReady.listen(...)`, never a stringly `listen('update-ready')`.
 * Fires (at most) once per run, the moment a background check finishes installing.
 */
export type UpdateReady = { version: string }
/**
 * What crosses to the console — mirrors the react port `WindowService.chrome()` verbatim
 * (`{ titleBar: 'overlay' | 'native' }`); the serde test below pins that shape.
 */
export type WindowChrome = { titleBar: TitleBar }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
