/**
 * Public entry for the desktop shell's typed Tauri commands AND events.
 *
 * `bindings.ts` is generated by tauri-specta on the Rust side (`cargo test`) and
 * committed + drift-checked — do not edit it by hand. Consumers import the typed
 * command surface from `@codm/app-tauri/commands`, never the generated file directly.
 *
 * `events` is the same idea for the other direction: the host pushes, and the listener is typed by
 * the Rust event struct (`events.supervisionChanged.listen`), so a stringly event name cannot drift
 * out of sync with what the shell emits.
 */
export { commands, events, type Result } from './bindings'
export type { SidecarFailure, SupervisionState } from './bindings'
