/**
 * Public entry for the desktop shell's typed Tauri commands.
 *
 * `bindings.ts` is generated by tauri-specta on the Rust side (`cargo test`) and
 * committed + drift-checked — do not edit it by hand. Consumers import the typed
 * command surface from `@codm/app-tauri/commands`, never the generated file directly.
 */
export { commands, type Result } from './bindings'
