import type { ComponentProps, ComponentType } from 'react'
import type { TablerIcon } from '@tabler/icons-react'

/**
 * App-specific icons (stripped of internal gradients / theme color logic).
 *
 * Each icon paints with `currentColor` so it can be tinted by any Tailwind text
 * utility (e.g. `text-primary`, `text-foreground`).
 *
 * Auto-generated from /tmp/gen-icon-index.mjs.
 */
export { default as AddIcon } from './add'
export { default as AddAltIcon } from './addAlt'
export { default as AddKitIcon } from './addKit'
export { default as AddUserIcon } from './addUser'
export { default as AlertIcon } from './alert'
export { default as ArrowIcon } from './arrow'
export { default as ArrowDownUpIcon } from './arrowDownUp'
export { default as ArrowLeftIcon } from './arrowLeft'
export { default as BackIcon } from './back'
export { default as BagIcon } from './bag'
export { default as BalanceIcon } from './balance'
export { default as BarCodeIcon } from './barCode'
export { default as BarGraphIcon } from './barGraph'
export { default as BellIcon } from './bell'
export { default as BkLogoIcon } from './bkLogo'
export { default as BotIcon } from './bot'
export { default as BoxIcon } from './box'
export { default as BoxSearchIcon } from './boxSearch'
export { default as BulbIcon } from './bulb'
export { default as CalculatorIcon } from './calculator'
export { default as CalendarIcon } from './calendar'
export { default as CardIcon } from './card'
export { default as CaretUpIcon } from './caretUp'
export { default as CartIcon } from './cart'
export { default as CashIcon } from './cash'
export { default as CheckIcon } from './check'
export { default as CheckLineIcon } from './checkLine'
export { default as CheckOutlinedIcon } from './checkOutlined'
export { default as CheckoutCheckIcon } from './checkoutCheck'
export { default as ChevronRightIcon } from './chevronRight'
export { default as ClickIcon } from './click'
export { default as ClipIcon } from './clip'
export { default as ClipboardIcon } from './clipboard'
export { default as CloseIcon } from './close'
export { default as CodmLogoIcon } from './codmLogo'
export { default as CurrencyMoneyIcon } from './currencyMoney'
export { default as DashLogoIcon } from './dashLogo'
export { default as DashboardIcon } from './dashboard'
export { default as DateIcon } from './date'
export { default as DocumentSearchIcon } from './documentSearch'
export { default as EditIcon } from './edit'
export { default as EditOutlinedIcon } from './editOutlined'
export { default as EllipsisIcon } from './ellipsis'
export { default as EmailIcon } from './email'
export { default as EmailAltIcon } from './emailAlt'
export { default as EngineIcon } from './engine'
export { default as Engine2Icon } from './engine2'
export { default as FailedIcon } from './failed'
export { default as FileIcon } from './file'
export { default as FilterIcon } from './filter'
export { default as GiftIcon } from './gift'
export { default as GradientBoxIcon } from './gradientBox'
export { default as GradientBoxOpenIcon } from './gradientBoxOpen'
export { default as GradientTruckIcon } from './gradientTruck'
export { default as GroupIcon } from './group'
export { default as HeartIcon } from './heart'
export { default as HideIcon } from './hide'
export { default as HomeIcon } from './home'
export { default as ImageIcon } from './image'
export { default as ImagePlaceholderIcon } from './imagePlaceholder'
export { default as InfoIcon } from './info'
export { default as LineIcon } from './line'
export { default as LineGraphIcon } from './lineGraph'
export { default as ListIcon } from './list'
export { default as LoadingIcon } from './loading'
export { default as LockIcon } from './lock'
export { default as LossIcon } from './loss'
export { default as MegaphoneIcon } from './megaphone'
export { default as MessageIcon } from './message'
export { default as MessageAltIcon } from './messageAlt'
export { default as MicrophoneIcon } from './microphone'
export { default as MoneyIcon } from './money'
export { default as MoneyBagIcon } from './moneyBag'
export { default as MoneyBoxIcon } from './moneyBox'
export { default as MoneyEngineIcon } from './moneyEngine'
export { default as MoneyMegaphoneIcon } from './moneyMegaphone'
export { default as NotificationErrorIcon } from './notificationError'
export { default as NotificationInfoIcon } from './notificationInfo'
export { default as OrderBlockIcon } from './orderBlock'
export { default as OrderCheckIcon } from './orderCheck'
export { default as OrderDownIcon } from './orderDown'
export { default as OrderUpIcon } from './orderUp'
export { default as PaperPlaneIcon } from './paperPlane'
export { default as PencilIcon } from './pencil'
export { default as PercentageIcon } from './percentage'
export { default as PhoneIcon } from './phone'
export { default as PixIcon } from './pix'
export { default as PixColorlessIcon } from './pixColorless'
export { default as PlusIcon } from './plus'
export { default as ProfileBlockIcon } from './profileBlock'
export { default as ProfileCheckIcon } from './profileCheck'
export { default as ProfitIcon } from './profit'
export { default as QuestionIcon } from './question'
export { default as RefreshIcon } from './refresh'
export { default as RefundIcon } from './refund'
export { default as ReturnIcon } from './return'
export { default as ScheduleMessageIcon } from './scheduleMessage'
export { default as SearchIcon } from './search'
export { default as SendIcon } from './send'
export { default as SendAltIcon } from './sendAlt'
export { default as SmsIcon } from './sms'
export { default as StarIcon } from './star'
export { default as StoreIcon } from './store'
export { default as SuccessIcon } from './success'
export { default as SwitchIcon } from './switch'
export { default as TagIcon } from './tag'
export { default as TicketIcon } from './ticket'
export { default as ToolIcon } from './tool'
export { default as ToolBoxIcon } from './toolBox'
export { default as TrafficIconIcon } from './trafficIcon'
export { default as TrashIcon } from './trash'
export { default as TrashOutlineIcon } from './trashOutline'
export { default as TriangleIcon } from './triangle'
export { default as TruckIcon } from './truck'
export { default as TurnoffIcon } from './turnoff'
export { default as UndoIcon } from './undo'
export { default as UploadIcon } from './upload'
export { default as UserIcon } from './user'
export { default as VideoIcon } from './video'
export { default as ViewIcon } from './view'
export { default as WarnIcon } from './warn'
export { default as WarningFilledIcon } from './warningFilled'
export { default as WhatsappIcon } from './whatsapp'
export { default as WhatsappAltIcon } from './whatsappAlt'
export { default as WhatsappColorIcon } from './whatsappColor'
export { default as XIcon } from './x'

/** A custom SVG icon from this folder (forwardRef over <svg> props). */
export type SvgIconComponent = ComponentType<ComponentProps<'svg'>>

/**
 * Canonical icon-component type — every icon the app renders is either one of the
 * custom SVG icons in this folder OR a Tabler icon.
 */
export type IconComponent = SvgIconComponent | TablerIcon
