/**
 * Aggregate lib.rs renderer for the Rust client crate — mod decls + `Client` +
 * `ClientBuilder`, one field/setter per discovered api service (symmetric with the
 * TS/Go SDK aggregates). Ported from template-fullstack; the per-service modules
 * themselves are progenitor output driven by generators/rust/index.ts.
 */
import { rustModIdent } from '../sanitize'
import type { ApiSource } from '../discover'

export interface ServiceMeta {
	source: ApiSource
}

export function renderLibRs(metas: ServiceMeta[]): string {
	const modDecls = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.service)
			return `#[path = "${m.source.service}/mod.rs"]\npub mod ${raw ? `r#${ident}` : ident};`
		})
		.join('\n\n')

	const fields = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.service)
			const use_ = raw ? `r#${ident}` : ident
			return `\tpub ${use_}: ${use_}::Client,`
		})
		.join('\n')

	const builderFields = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.service)
			return `\t${raw ? `r#${ident}` : ident}_url: Option<String>,`
		})
		.join('\n')

	const builderSetters = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.service)
			const use_ = raw ? `r#${ident}` : ident
			return `\tpub fn ${use_}(mut self, url: impl Into<String>) -> Self {\n\t\tself.${use_}_url = Some(url.into());\n\t\tself\n\t}`
		})
		.join('\n\n')

	const buildInits = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.service)
			const use_ = raw ? `r#${ident}` : ident
			return `\t\t\t${use_}: ${use_}::Client::new_with_client(self.${use_}_url.as_deref().ok_or(BuildError::MissingUrl("${m.source.service}"))?, http.clone()),`
		})
		.join('\n')

	return `//! AUTO-GENERATED by packages/client/generators/rust/index.ts — do not edit.
#![allow(clippy::all)]
#![allow(unused_imports)]
#![allow(renamed_and_removed_lints)]

${modDecls}

#[derive(Debug, thiserror::Error)]
pub enum BuildError {
	#[error("missing url for service: {0}")]
	MissingUrl(&'static str),
}

pub struct Client {
${fields}
}

#[derive(Default)]
pub struct ClientBuilder {
${builderFields}
	http: Option<reqwest::Client>,
}

impl ClientBuilder {
	pub fn new() -> Self { Self::default() }

${builderSetters}

	pub fn http(mut self, c: reqwest::Client) -> Self { self.http = Some(c); self }

	pub fn build(self) -> Result<Client, BuildError> {
		let http = self.http.unwrap_or_default();
		Ok(Client {
${buildInits}
		})
	}
}

impl Client {
	pub fn builder() -> ClientBuilder { ClientBuilder::new() }
}
`
}
