/**
 * Aggregate lib.rs renderer for the Rust client crate — mod decls + `Client` +
 * `ClientBuilder`, one field/setter per discovered api service (symmetric with the
 * TS/Go SDK aggregates). Ported from template-fullstack; the per-service modules
 * themselves are progenitor output driven by generators/rust/index.ts.
 *
 * ── CHAVEIA POR `clientId`, NUNCA POR `service` ──────────────────────────────────────────────────
 * Desde o ADR 0001 o MESMO serviço publica DUAS superfícies (o daemon local e o deployment de
 * nuvem), e `discoverApis` devolve uma fonte por (serviço, perfil). `service` é `'typescript'` nas
 * duas; só `clientId` distingue (`typescript` × `typescript-cloud`).
 *
 * Este arquivo chaveava por `service` e emitia `pub mod typescript;` DUAS VEZES — o crate parava de
 * compilar com *the name `typescript` is defined multiple times*, e junto com ele o shell Tauri, que
 * o tem como dependência de caminho. Os geradores TS e Go já usavam `clientId`; só este ficou para
 * trás, e nada reprovava.
 */
import { rustModIdent } from '../sanitize'
import type { ApiSource } from '../discover'

export interface ServiceMeta {
	source: ApiSource
}

export function renderLibRs(metas: ServiceMeta[]): string {
	const modDecls = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.clientId)
			return `#[path = "${m.source.clientId}/mod.rs"]\npub mod ${raw ? `r#${ident}` : ident};`
		})
		.join('\n\n')

	const fields = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.clientId)
			const use_ = raw ? `r#${ident}` : ident
			return `\tpub ${use_}: ${use_}::Client,`
		})
		.join('\n')

	const builderFields = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.clientId)
			return `\t${raw ? `r#${ident}` : ident}_url: Option<String>,`
		})
		.join('\n')

	const builderSetters = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.clientId)
			const use_ = raw ? `r#${ident}` : ident
			return `\tpub fn ${use_}(mut self, url: impl Into<String>) -> Self {\n\t\tself.${use_}_url = Some(url.into());\n\t\tself\n\t}`
		})
		.join('\n\n')

	const buildInits = metas
		.map(m => {
			const { raw, ident } = rustModIdent(m.source.clientId)
			const use_ = raw ? `r#${ident}` : ident
			return `\t\t\t${use_}: ${use_}::Client::new_with_client(self.${use_}_url.as_deref().ok_or(BuildError::MissingUrl("${m.source.clientId}"))?, http.clone()),`
		})
		.join('\n')

	return `//! AUTO-GENERATED by packages/client/generators/rust/index.ts — do not edit.
#![allow(clippy::all)]
#![allow(unused_imports)]
#![allow(renamed_and_removed_lints)]

${modDecls}

#[derive(Debug, thiserror::Error)]
pub enum BuildError {
	#[error("missing url for service: {0}")]
	MissingUrl(&'static str),
}

pub struct Client {
${fields}
}

#[derive(Default)]
pub struct ClientBuilder {
${builderFields}
	http: Option<reqwest::Client>,
}

impl ClientBuilder {
	pub fn new() -> Self { Self::default() }

${builderSetters}

	pub fn http(mut self, c: reqwest::Client) -> Self { self.http = Some(c); self }

	pub fn build(self) -> Result<Client, BuildError> {
		let http = self.http.unwrap_or_default();
		Ok(Client {
${buildInits}
		})
	}
}

impl Client {
	pub fn builder() -> ClientBuilder { ClientBuilder::new() }
}
`
}
