import { mkdir, writeFile, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFile } from 'node:fs/promises'
import {
	parseContractsOpenapi,
	type ParsedEnum,
	type ParsedUnion,
	type ParsedEvent,
	type FieldType,
	type EventField,
} from './lib/parse-openapi'
import { assertIntegrationWireNames } from './lib/assert-wire-names'
import { assertUnionSlotOwners, type UnionSlotDecl, type UnionVariantDecl } from './lib/union-slots'
import { REPO } from '../../../template.config'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const INPUT = join(ROOT, 'dist/contracts.openapi.yaml')
const OUTPUT = join(ROOT, 'generated/typescript/src/wire')

const HEADER = `// AUTO-GENERATED by packages/contracts/codegen/emit-wire-ts.ts — do not edit.\n`

function kebab(name: string): string {
	return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

/**
 * Convert an enum value string to a valid TypeScript identifier.
 * For values that are already valid identifiers (e.g. "EXAMPLE"), this is a no-op.
 * For dotted namespaced values (e.g. "sync.external_order_updated"), the leading
 * namespace segment (everything up to and including the first ".") is stripped before
 * uppercasing + replacing remaining non-identifier chars with "_". This currently
 * serves the only dotted enum in the contracts: SyncEventName.
 * "sync.external_order_updated" → strip "sync." → "external_order_updated" → "EXTERNAL_ORDER_UPDATED"
 */
function toTsEnumMember(v: string): string {
	if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(v)) return v
	// Strip the leading namespace segment (up to and including the first dot), then
	// uppercase and replace any remaining non-identifier characters with underscores.
	const stripped = v.includes('.') ? v.slice(v.indexOf('.') + 1) : v
	const ident = stripped.toUpperCase().replace(/[^A-Z0-9_$]/g, '_')
	// A TS enum member name cannot lead with a digit (e.g. "1m" → "1M" is invalid) —
	// prefix "_" so it stays a legal identifier ("1m" → "_1M"). OpenAPI drops the
	// TypeSpec member name, so the label is value-derived; the wire VALUE is exact.
	return /^[0-9]/.test(ident) ? `_${ident}` : ident
}

export function emitTsEnums(enums: ParsedEnum[]): Record<string, string> {
	const files: Record<string, string> = {}
	const indexLines: string[] = []

	for (const e of enums) {
		const file = `${kebab(e.name)}.ts`
		const members = e.values.map(v => `\t${toTsEnumMember(v)} = '${v}',`).join('\n')
		const body = `${HEADER + (e.doc ? `/** ${e.doc} */\n` : '')}export enum ${e.name} {\n${members}\n}\n`
		files[file] = body
		indexLines.push(`export * from './${kebab(e.name)}'`)
	}

	files['index.ts'] = `${HEADER + indexLines.sort().join('\n')}\n`
	return files
}

export function emitTsUnions(unions: ParsedUnion[]): Record<string, string> {
	const files: Record<string, string> = {}
	const indexLines: string[] = []
	for (const u of unions) {
		const members = u.refs.map(r => `z.enum(${r})`).join(', ')
		const body =
			HEADER +
			`import { z } from '${REPO.corePackage}/schema'\n` +
			`import { ${u.refs.join(', ')} } from '../enums'\n\n` +
			(u.doc ? `/** ${u.doc} */\n` : '') +
			`export const ${u.name}Schema = z.union([${members}])\n`
		files[`${kebab(u.name)}.ts`] = body
		indexLines.push(`export * from './${kebab(u.name)}'`)
	}
	files['index.ts'] = `${HEADER + indexLines.sort().join('\n')}\n`
	return files
}

// Enum/union refs can be nested inside array items (e.g. `providers: ProviderKind[]`), so the
// import collector must descend into `array` element types — a top-level-only filter would emit
// `z.array(z.enum(ProviderKind))` without importing ProviderKind. Mirrors zodExpr's recursion.
function collectEnumRefs(t: FieldType): string[] {
	if (t.kind === 'enum-ref') return [t.ref]
	if (t.kind === 'array') return collectEnumRefs(t.items)
	return []
}

function collectUnionRefs(t: FieldType): string[] {
	if (t.kind === 'union-ref') return [t.ref]
	if (t.kind === 'array') return collectUnionRefs(t.items)
	return []
}

function zodExpr(t: FieldType): string {
	switch (t.kind) {
		case 'string':
			return 'z.string()'
		case 'uuid':
			return 'z.uuid()'
		case 'literal':
			return `z.literal('${t.value}')`
		case 'string-enum':
			return `z.enum([${t.values.map(v => `'${v}'`).join(', ')}])`
		case 'enum-ref':
			return `z.enum(${t.ref})`
		case 'union-ref':
			return `${t.ref}Schema`
		case 'boolean':
			return 'z.boolean()'
		case 'integer':
			return 'z.number().int()'
		case 'number':
			return 'z.number()'
		case 'date-time':
			return 'z.date()'
		case 'url':
			return 'z.string().url()'
		case 'array':
			return `z.array(${zodExpr(t.items)})`
		case 'unknown':
			return 'z.unknown()'
	}
}

/**
 * Union-slot MANIFEST export (union-slots spec §2.2) — slot → discriminators →
 * [{values, typeName, owner}]. Consumed by the union-parity rail and by surface
 * composition; the variant SHAPES themselves live with the owner workspace and reach
 * consumers ONLY through the owner's generated client schemas.
 */
function unionManifestSource(ev: ParsedEvent): string {
	const name = `${ev.modelName.replace(/Event$/, '')}Unions`
	const lines: string[] = []
	lines.push('/** Union-slot manifest — the variant shapes live with the owner workspace (see union-slots spec). */')
	lines.push(`export const ${name} = {`)
	for (const slot of ev.unionSlots) {
		lines.push(`\t${slot.field}: {`)
		lines.push(`\t\tdiscriminators: [${slot.discriminators.map(d => `'${d}'`).join(', ')}],`)
		lines.push('\t\tvariants: [')
		for (const v of slot.variants) {
			lines.push(`\t\t\t{ values: [${v.values.map(x => `'${x}'`).join(', ')}], typeName: '${v.typeName}', owner: '${v.owner}' },`)
		}
		lines.push('\t\t],')
		lines.push('\t},')
	}
	lines.push('} as const')
	return lines.join('\n')
}

export function emitTsEvents(events: ParsedEvent[]): Record<string, string> {
	assertIntegrationWireNames(events)
	const files: Record<string, string> = {}

	for (const ev of events) {
		// Payload = the model's OWN declarations (declaration order), minus the wire
		// discriminator + entity id. Envelope fields a model explicitly REDECLARES
		// (verbatim payloads carrying ownerId/occurredAt inside the payload) stay in.
		const payloadFields = ev.ownFields.filter(f => f.name !== 'name' && f.name !== 'entityId')

		const enumRefs = payloadFields.flatMap(f => collectEnumRefs(f.type))
		const enumImports = [...new Set(enumRefs)].sort()
		const importLines = [
			`import { z } from '${REPO.corePackage}/schema'`,
			`import { BaseIntegrationEvent } from '${REPO.corePackage}/events'`,
		]
		if (enumImports.length > 0) {
			const names = enumImports.join(', ')
			importLines.push(`import { ${names} } from '../enums'`)
		}
		const unionRefs = payloadFields.flatMap(f => collectUnionRefs(f.type))
		const unionImports = [...new Set(unionRefs)].sort()
		if (unionImports.length > 0) {
			importLines.push(`import { ${unionImports.map(r => `${r}Schema`).join(', ')} } from '../unions'`)
		}

		const zodFields = payloadFields.map(f => `\t${f.name}: ${zodExpr(f.type)}${f.required ? '' : '.optional()'},`).join('\n')

		const body =
			HEADER +
			importLines.join('\n') +
			'\n\n' +
			(ev.doc ? `/** ${ev.doc} */\n` : '') +
			`export const ${ev.modelName}Schema = z.integrationEvent('${ev.wireName}', {\n${zodFields}\n})\n\n` +
			`export class ${ev.modelName} extends BaseIntegrationEvent<typeof ${ev.modelName}Schema> {\n` +
			`\tstatic override readonly name = '${ev.wireName}' as const\n` +
			`\tstatic readonly schema = ${ev.modelName}Schema\n` +
			`}\n` +
			(ev.unionSlots.length > 0 ? `\n${unionManifestSource(ev)}\n` : '')

		files[`${kebab(ev.modelName.replace(/Event$/, ''))}.ts`] = body
	}

	return files
}

const camel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1)

/**
 * The MATERIALIZED wire-event surface (union-slots spec §2.4) — the manifest×aggregate join done
 * ONCE, at the wire-processing layer (founder direction 23-jul: the union arrives pre-materialized
 * from the generated layer, like the medscall monorepo; re-emitting controllers only compose).
 *
 * For every contract event this emits a `<Model>MaterializedSchema`:
 *   - event WITH a `<Model>Unions` manifest → the contract schema with `payload` swapped for the
 *     OWNER workspace's generated aggregate payload schema (`<camel(model)>PayloadSchema`, imported
 *     from the owner's client subpath) — the COMPLETE materialized oneOf;
 *   - event WITHOUT a manifest → the pure contract schema, aliased.
 * Plus the deterministic (wire-name-sorted) tuple + discriminated union over the whole surface.
 *
 * A manifest whose variants span MORE than one owner cannot materialize a single aggregate payload
 * — that is a contract error and the generator fails loud.
 */
export function emitTsMaterialized(events: ParsedEvent[], workspaces: Record<string, { alias: string }>, sdkPackage: string): string {
	interface Entry {
		modelName: string
		wireName: string
		ownerAlias?: string
		payloadSchemaId?: string
	}
	const entries: Entry[] = events.map(ev => {
		if (ev.unionSlots.length === 0) return { modelName: ev.modelName, wireName: ev.wireName }
		const owners = new Set(ev.unionSlots.flatMap(s => s.variants.map(v => v.owner)))
		if (owners.size !== 1) {
			throw new Error(
				`${ev.modelName}: union-slot variants span ${owners.size} owners (${[...owners].join(', ')}) — a materialized payload needs exactly one owner`,
			)
		}
		const owner = [...owners][0]!
		const ws = workspaces[owner]
		if (!ws) throw new Error(`${ev.modelName}: union-slot owner "${owner}" is not a WORKSPACES id`)
		const model = ev.modelName.replace(/Event$/, '')
		return { modelName: ev.modelName, wireName: ev.wireName, ownerAlias: ws.alias, payloadSchemaId: `${camel(model)}PayloadSchema` }
	})

	// Deterministic wire-name ordering — the daemon's SSE output union (and therefore its emitted
	// openapi) is derived from this tuple's order.
	const sorted = [...entries].sort((a, b) => a.wireName.localeCompare(b.wireName))

	const byAlias = new Map<string, string[]>()
	for (const e of entries) {
		if (!e.ownerAlias || !e.payloadSchemaId) continue
		const ids = byAlias.get(e.ownerAlias) ?? []
		if (!ids.includes(e.payloadSchemaId)) ids.push(e.payloadSchemaId)
		byAlias.set(e.ownerAlias, ids)
	}
	const clientImports = [...byAlias.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([alias, ids]) => `import { ${ids.sort().join(', ')} } from '${sdkPackage}/${alias}'`)

	const schemaLines = entries.map(e =>
		e.payloadSchemaId
			? `export const ${e.modelName}MaterializedSchema = ${e.modelName}Schema.extend({ payload: ${e.payloadSchemaId} })`
			: `export const ${e.modelName}MaterializedSchema = ${e.modelName}Schema`,
	)

	const tuple = sorted.map(e => `\t${e.modelName}MaterializedSchema,`).join('\n')

	return (
		HEADER +
		'//\n' +
		'// REGENERATION ORDER (build-graph note): this module lives in the CONTRACTS bindings but\n' +
		`// imports the owner services' generated client schemas (${sdkPackage}/<service>) — the\n` +
		'// pipeline is contracts → owner openapi → client (kubb) → this surface type-checks. After\n' +
		'// adding a union-slot manifest to the contract, run `bun sdk` so the owner client exports\n' +
		'// the aggregate payload schema these imports resolve against; until then tsc fails LOUD\n' +
		'// (a broken codegen chain must never emit an opaque frame).\n' +
		`import { z } from '${REPO.corePackage}/schema'\n` +
		`import Z from 'zod'\n` +
		`import {\n${events.map(e => `\t${e.modelName}Schema,`).join('\n')}\n} from './_imports'\n` +
		clientImports.join('\n') +
		'\n\n' +
		schemaLines.join('\n') +
		'\n\n' +
		'/** Every materialized event schema, sorted by wire name (deterministic emission order). */\n' +
		`export const materializedIntegrationEventSchemas = [\n${tuple}\n] as const\n\n` +
		`export const MaterializedIntegrationEventSchema = z.discriminatedUnion('name', [\n${tuple}\n])\n` +
		`export type MaterializedIntegrationEvent = Z.infer<typeof MaterializedIntegrationEventSchema>\n`
	)
}

/** Kubb's identifier for a bare variant type: FIRST character lowercased, the rest verbatim
 *  (WhatsAppTextContent → whatsAppTextContentSchema; WhatsAppQRCodeUpdated → whatsAppQRCodeUpdatedSchema). */
const variantSchemaId = (typeName: string) => `${camel(typeName)}Schema`

/** Zip a slot's (JSON-name) discriminators with a variant's POSITIONAL values. The TS manifest keys
 *  values positionally; the Go manifest keys them by field name — this is the adapter that makes the
 *  join predicate below comparable across the two sides. */
function pinnedOf(slot: UnionSlotDecl, v: UnionVariantDecl): Record<string, string> {
	const out: Record<string, string> = {}
	slot.discriminators.forEach((d, i) => {
		out[d] = v.values[i] as string
	})
	return out
}

/** PRIMARY slot — argmax by VARIANT COUNT, first-declared wins ties. Verbatim from
 *  `packages/api/go/pkg/openapi/schema.go` (`>`, not `>=`). NOT argmax by discriminator arity —
 *  that is the *association* rule in `lib/union-slots.ts`, a different question. */
function primarySlotOf(slots: readonly UnionSlotDecl[]): UnionSlotDecl {
	let primary = slots[0] as UnionSlotDecl
	for (const s of slots) if (s.variants.length > primary.variants.length) primary = s
	return primary
}

/** THE CROSS-SLOT JOIN, mirrored from Go's `secondarySlotSchema`. A secondary variant survives iff
 *  every discriminator key it SHARES with the pinned primary variant carries the same value; keys
 *  present on only one side impose no constraint. Zero survivors ⇒ NO narrowing at all — the full
 *  slot union. That widening is reproduced deliberately rather than improved on: the two emitters
 *  must agree by construction, and diverging here would desync the surfaces silently. */
function joinSecondary(sec: UnionSlotDecl, pinned: Record<string, string>): readonly UnionVariantDecl[] {
	const matching = sec.variants.filter(sv => Object.entries(pinnedOf(sec, sv)).every(([k, val]) => !(k in pinned) || pinned[k] === val))
	return matching.length === 0 ? sec.variants : matching
}

/** `z.literal(...)` for a pinned discriminator, in the CONTRACT's own value type — an enum-backed
 *  discriminator gets the ENUM MEMBER (`z.literal(MessageType.TEXT)`) because that is what the
 *  contract declares; a `z.string()` discriminator gets a bare string literal and must NOT be
 *  "upgraded" to an enum member it was never typed as. */
function discriminatorLiteral(field: EventField, value: string): string {
	return field.type.kind === 'enum-ref' ? `z.literal(${field.type.ref}.${toTsEnumMember(value)})` : `z.literal('${value}')`
}

/**
 * The IN-PROCESS wire-event surface — the SECOND materialization (union-slots spec §2.4).
 *
 * Two materializations exist, they are NOT interchangeable, and what separates them is the SCALAR
 * DIALECT rather than how much they narrow (both narrow fully):
 *
 *   ./materialized  `<Model>EventMaterializedSchema` — the JSON/HTTP surface. Its payload IS the
 *                   owner client's kubb aggregate, so `occurredAt`/`observedAt` are ISO STRINGS.
 *                   That is CORRECT for its consumer (an SSE frame is JSON on the wire) and FROZEN.
 *   ./in-process    `<Model>InProcessEventSchema` — the MEDIATOR surface. The mediator revives ISO
 *                   strings into `Date`s before a handler ever sees the envelope (core's
 *                   `reviveIsoDates`), so the arms are built from the CONTRACT payload object:
 *                   every scalar keeps its contract type (`occurredAt: z.date()`) and ONLY the slot
 *                   fields plus the discriminators that pin them are replaced, per variant, with the
 *                   owner client's PER-VARIANT schemas.
 *
 * Materialized FOR THE WIRE vs materialized FOR THIS PROCESS — pick by where the frame is going.
 * Handing a handler the wire surface fails loudly on the first `Date` field, which is the point.
 *
 * The arm SET mirrors `packages/api/go/pkg/openapi/schema.go` exactly — primary selection, the
 * cross-slot join, the zero-match fallback, and the field-override walk in payload DECLARATION
 * order — so the Go openapi and this surface agree by construction rather than by review. The
 * declaration-order walk is also what makes emission byte-stable for `bun check:generated`.
 *
 * Emitted ONLY for events that declare a union-slot manifest: a slot-less event's contract class
 * already narrows, so a second class for it would be pure noise. Deliberately emits NO tuple and NO
 * `z.discriminatedUnion` — these schemas share a wire `name` with their contract twin, and zod v4
 * does not reject a duplicate discriminator at CONSTRUCTION, only on the first parse. A tuple here
 * would be a landmine that detonates far from the edit that armed it.
 *
 * NOTE the validity asymmetry, on purpose: `emitTsMaterialized` hard-throws on a manifest whose
 * variants span more than one owner, and `run()` writes it FIRST. This emitter resolves owners
 * per-variant and relies on that gate rather than restating it — do not "fix" the asymmetry by
 * deleting the throw over there.
 */
export function emitTsInProcess(events: ParsedEvent[], workspaces: Record<string, { alias: string }>, sdkPackage: string): string {
	// Sorted by model name so emission never depends on OpenAPI component ordering. ONE comparator
	// (`localeCompare`) is used for every sort in this function — mixing it with codepoint `.sort()`
	// produces genuinely different orders and a diff that looks like drift.
	const byName = (a: string, b: string) => a.localeCompare(b)
	const slotted = events.filter(ev => ev.unionSlots.length > 0).sort((a, b) => byName(a.modelName, b.modelName))
	if (slotted.length === 0) return `${HEADER}\nexport {}\n`

	const enumRefs = new Set<string>()
	const byAlias = new Map<string, Set<string>>()
	const blocks: string[] = []

	/** Record the owner-client import this arm needs and return the identifier to emit. */
	const bind = (ev: ParsedEvent, v: UnionVariantDecl): string => {
		const ws = workspaces[v.owner]
		if (!ws) throw new Error(`${ev.modelName}: @variant "${v.typeName}" declares owner "${v.owner}", which is not a WORKSPACES id`)
		const ids = byAlias.get(ws.alias) ?? new Set<string>()
		ids.add(variantSchemaId(v.typeName))
		byAlias.set(ws.alias, ids)
		return variantSchemaId(v.typeName)
	}

	for (const ev of slotted) {
		const model = ev.modelName.replace(/Event$/, '')
		// The same payload projection `emitTsEvents` uses — the arms extend THAT object.
		const payloadFields = ev.ownFields.filter(f => f.name !== 'name' && f.name !== 'entityId')
		const fieldByName = new Map(payloadFields.map(f => [f.name, f]))
		const primary = primarySlotOf(ev.unionSlots)
		const secondaries = ev.unionSlots.filter(s => s.field !== primary.field)

		// Fail LOUD rather than silently widen: a slot or discriminator that lives on the ENVELOPE
		// instead of the payload cannot be replaced or pinned by an arm.
		for (const slot of ev.unionSlots) {
			if (!fieldByName.has(slot.field)) {
				throw new Error(`${ev.modelName}: union slot "${slot.field}" is not a payload field — the in-process arms cannot replace it`)
			}
		}
		for (const d of primary.discriminators) {
			if (!fieldByName.has(d)) {
				throw new Error(`${ev.modelName}: primary discriminator "${d}" is not a payload field — the in-process arms cannot pin it`)
			}
		}

		const armBodies: string[][] = primary.variants.map(pv => {
			const pinned = pinnedOf(primary, pv)
			const lines: string[] = []
			for (const f of payloadFields) {
				let expr: string | undefined
				if (primary.discriminators.includes(f.name)) {
					// (a) a PRIMARY discriminator this variant pins → the literal. Literals come ONLY from
					// the primary's discriminator list; a secondary-only discriminator gets none and stays
					// a plain typed field, exactly as the Go emitter leaves it.
					expr = discriminatorLiteral(f, pinned[f.name] as string)
					if (f.type.kind === 'enum-ref') enumRefs.add(f.type.ref)
				} else if (f.name === primary.field) {
					// (b) the primary slot field → this variant's shape.
					expr = bind(ev, pv)
				} else {
					// (c) a SECONDARY slot → the join, narrowed by the pinned values.
					const sec = secondaries.find(s => s.field === f.name)
					if (sec) {
						const kept = joinSecondary(sec, pinned)
						expr = kept.length === 1 ? bind(ev, kept[0] as UnionVariantDecl) : `z.union([${kept.map(v => bind(ev, v)).join(', ')}])`
					}
				}
				// (d) every OTHER field is NOT re-emitted — it keeps the CONTRACT schema, which is the whole
				// point of this surface: `occurredAt` stays `z.date()` and the arm stays honest for a
				// revived envelope.
				if (expr) lines.push(`${f.name}: ${expr}${f.required ? '' : '.optional()'},`)
			}
			return lines
		})

		const renderArms = (indent: string) =>
			armBodies.map(
				fields => `${indent}${ev.modelName}Schema.shape.payload.extend({\n${fields.map(l => `${indent}\t${l}`).join('\n')}\n${indent}})`,
			)
		const payloadExpr =
			armBodies.length === 1 ? (renderArms('\t')[0] as string).trimStart() : `z.union([\n${renderArms('\t\t').join(',\n')},\n\t])`

		blocks.push(
			`export const ${model}InProcessEventSchema = ${ev.modelName}Schema.extend({\n\tpayload: ${payloadExpr},\n})\n\n` +
				`export class ${model}InProcessEvent extends BaseIntegrationEvent<typeof ${model}InProcessEventSchema> {\n` +
				`\tstatic override readonly name = '${ev.wireName}' as const\n` +
				`\tstatic readonly schema = ${model}InProcessEventSchema\n` +
				`}`,
		)
	}

	const importLines = [
		`import { z } from '${REPO.corePackage}/schema'`,
		`import { BaseIntegrationEvent } from '${REPO.corePackage}/events'`,
		`import {\n${slotted
			.map(e => `\t${e.modelName}Schema,`)
			.sort(byName)
			.join('\n')}\n} from './_imports'`,
	]
	if (enumRefs.size > 0) importLines.push(`import { ${[...enumRefs].sort(byName).join(', ')} } from '../enums'`)
	for (const [alias, ids] of [...byAlias.entries()].sort(([a], [b]) => byName(a, b))) {
		importLines.push(`import { ${[...ids].sort(byName).join(', ')} } from '${sdkPackage}/${alias}'`)
	}

	return (
		HEADER +
		'//\n' +
		'// The IN-PROCESS event surface: the union-slot join done against the CONTRACT payload object,\n' +
		'// so every scalar keeps its contract type (`occurredAt: z.date()`). This is the surface an\n' +
		'// EventHandler binds to — the mediator revives ISO strings into Dates before `handle()` runs.\n' +
		'// Its sibling ./materialized is the JSON/HTTP (SSE/browser) surface, whose payload is the owner\n' +
		'// client aggregate and whose dates are ISO STRINGS. Same arm set, different scalar dialect:\n' +
		'// "materialized for the wire" vs "materialized for this process". Do not swap them — handing a\n' +
		'// handler the wire surface fails on the first Date field, which is exactly the intent.\n' +
		'// The arm set mirrors packages/api/go/pkg/openapi/schema.go (primary = argmax by variant count;\n' +
		'// secondary slots narrowed by equality on the INTERSECTION of discriminator keys).\n' +
		importLines.join('\n') +
		'\n\n' +
		blocks.join('\n\n') +
		'\n'
	)
}

export function emitTsBarrel(events: ParsedEvent[]): string {
	const names = events.map(e => e.modelName)
	const reExports = [
		...events.map(e => `export * from './${kebab(e.modelName.replace(/Event$/, ''))}'`),
		`export * from './in-process'`,
		`export * from './materialized'`,
	]
		.sort()
		.join('\n')
	const schemaImports = names.map(n => `\t${n}Schema,`).join('\n')
	const schemas = names.map(n => `\t${n}Schema`).join(',\n')
	return (
		HEADER +
		`import { z } from '${REPO.corePackage}/schema'\n` +
		`import Z from 'zod'\n` +
		`import {\n${schemaImports}\n} from './_imports'\n\n` +
		reExports +
		'\n\n' +
		`export const IntegrationEventSchema = z.discriminatedUnion('name', [\n${schemas},\n])\n` +
		`export type IntegrationEvent = Z.infer<typeof IntegrationEventSchema>\n`
	)
}

async function run() {
	const yamlText = await readFile(INPUT, 'utf-8')
	const parsed = parseContractsOpenapi(yamlText)
	// Hard gates BEFORE any rm/write — a bad contract must not wipe the committed bindings.
	assertIntegrationWireNames(parsed.events)
	// Unknown @variant owner = contract compilation error (validated against the WORKSPACES manifest).
	assertUnionSlotOwners(parsed.events, Object.keys(REPO.workspaces))

	const enumDir = join(OUTPUT, 'enums')
	const unionDir = join(OUTPUT, 'unions')
	const eventDir = join(OUTPUT, 'events')
	await rm(enumDir, { recursive: true, force: true })
	await rm(unionDir, { recursive: true, force: true })
	await rm(eventDir, { recursive: true, force: true })
	await mkdir(enumDir, { recursive: true })
	await mkdir(eventDir, { recursive: true })

	const enumFiles = emitTsEnums(parsed.enums)
	for (const [name, contents] of Object.entries(enumFiles)) {
		await writeFile(join(enumDir, name), contents)
	}
	// Only materialize the unions dir when there are unions — a zero-union contract
	// leaves no orphan files (the dir was unconditionally removed above).
	if (parsed.unions.length > 0) {
		await mkdir(unionDir, { recursive: true })
		const unionFiles = emitTsUnions(parsed.unions)
		for (const [name, contents] of Object.entries(unionFiles)) {
			await writeFile(join(unionDir, name), contents)
		}
	}

	const eventFiles = emitTsEvents(parsed.events)
	for (const [name, contents] of Object.entries(eventFiles)) {
		await writeFile(join(eventDir, name), contents)
	}

	const importsRe =
		HEADER +
		parsed.events
			.map(e => `export * from './${kebab(e.modelName.replace(/Event$/, ''))}'`)
			.sort()
			.join('\n') +
		'\n'
	await writeFile(join(eventDir, '_imports.ts'), importsRe)

	await writeFile(
		join(eventDir, 'materialized.ts'),
		emitTsMaterialized(parsed.events, REPO.workspaces as unknown as Record<string, { alias: string }>, REPO.sdkPackage),
	)

	await writeFile(
		join(eventDir, 'in-process.ts'),
		emitTsInProcess(parsed.events, REPO.workspaces as unknown as Record<string, { alias: string }>, REPO.sdkPackage),
	)

	await writeFile(join(eventDir, 'index.ts'), emitTsBarrel(parsed.events))

	const unionExport = parsed.unions.length > 0 ? `export * from './unions'\n` : ''
	const wireIndex = `${HEADER}export * from './enums'\n${unionExport}export * from './events'\n`
	await writeFile(join(OUTPUT, 'index.ts'), wireIndex)

	console.log(`✔ emitted ${parsed.enums.length} enums and ${parsed.events.length} events`)
}

if (import.meta.main) {
	await run()
}
