import { mkdir, writeFile, rm, readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
	parseContractsOpenapi,
	type ParsedEnum,
	type ParsedUnion,
	type ParsedEvent,
	type FieldType,
	type EventField,
} from './lib/parse-openapi'
import { assertIntegrationWireNames } from './lib/assert-wire-names'
import { assertUnionSlotOwners } from './lib/union-slots'
import { REPO } from '../../../template.config'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const INPUT = join(ROOT, 'dist/contracts.openapi.yaml')
const OUTPUT = join(ROOT, 'generated/go/wire')

const HEADER = `// AUTO-GENERATED by packages/contracts/codegen/emit-wire-go.ts — do not edit.\n`

function pascalToGoField(name: string): string {
	const out = name[0]!.toUpperCase() + name.slice(1)
	// Go initialisms: `Id`/`Ids`/`Url` become `ID`/`IDs`/`URL` so the generated
	// payload structs are drop-in-alias compatible with the hand-rolled medscall
	// field spellings (e.g. messageIds → MessageIDs, matching the envelopes the
	// flat-events swap replaces).
	return out.replace(/Ids\b/g, 'IDs').replace(/Id\b/g, 'ID').replace(/Url\b/g, 'URL')
}

function goType(t: FieldType): string {
	switch (t.kind) {
		case 'string':
			return 'string'
		case 'uuid':
			return 'uuid.UUID'
		case 'literal':
			return 'string'
		case 'string-enum':
			return 'string'
		case 'enum-ref':
			return t.ref
		case 'union-ref':
			return t.ref
		case 'boolean':
			return 'bool'
		case 'integer':
			return t.format === 'int64' ? 'int64' : 'int32'
		case 'number':
			return 'float64'
		case 'date-time':
			return 'time.Time'
		case 'url':
			return 'string'
		case 'array':
			return `[]${goType(t.items)}`
		case 'unknown':
			return 'json.RawMessage'
	}
}

/**
 * Convert an enum value string to a valid Go identifier suffix.
 * For values that are already valid identifiers (e.g. "EXAMPLE"), this is a no-op.
 * For dotted namespaced values (e.g. "sync.external_order_updated"), the leading
 * namespace segment (everything up to and including the first ".") is stripped before
 * uppercasing + replacing remaining non-identifier chars with "_". This currently
 * serves the only dotted enum in the contracts: SyncEventName.
 * "sync.external_order_updated" → strip "sync." → "external_order_updated" → "EXTERNAL_ORDER_UPDATED"
 */
function toGoEnumIdent(v: string): string {
	// If already a valid Go identifier suffix (letters, digits, underscores; no leading digit)
	if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(v)) return v
	// Strip the leading namespace segment (up to and including the first dot), then
	// uppercase and replace any remaining non-identifier characters with underscores.
	const stripped = v.includes('.') ? v.slice(v.indexOf('.') + 1) : v
	return stripped.toUpperCase().replace(/[^A-Z0-9_]/g, '_')
}

export function emitGoEnums(enums: ParsedEnum[]): string {
	const lines: string[] = [HEADER, 'package wire', '', 'import "fmt"', '']
	for (const e of enums) {
		lines.push(`type ${e.name} string`)
		lines.push('')
		lines.push('const (')
		for (const v of e.values) lines.push(`\t${e.name}${toGoEnumIdent(v)} ${e.name} = "${v}"`)
		lines.push(')')
		lines.push('')
		lines.push(`func Parse${e.name}(s string) (${e.name}, error) {`)
		lines.push(`\tswitch ${e.name}(s) {`)
		const cases = e.values.map(v => `${e.name}${toGoEnumIdent(v)}`).join(', ')
		lines.push(`\tcase ${cases}:`)
		lines.push(`\t\treturn ${e.name}(s), nil`)
		lines.push('\tdefault:')
		lines.push(`\t\treturn "", fmt.Errorf("invalid ${e.name}: %q", s)`)
		lines.push('\t}')
		lines.push('}')
		lines.push('')
	}
	return lines.join('\n')
}

export function emitGoUnions(unions: ParsedUnion[]): string {
	const lines: string[] = [HEADER, 'package wire', '']
	for (const u of unions) {
		lines.push(`// ${u.name} is a cross-category union of platform enums.`)
		if (u.doc) lines.push(`// ${u.doc}`)
		// Bridge annotation: read by core/pkg/openapi to emit a oneOf component.
		// `values=` lists the member enum TYPE names (each becomes a $ref).
		lines.push(`// @oneof values=${u.refs.join(',')}`)
		lines.push(`type ${u.name} string`)
		lines.push('')
		lines.push(`// Valid reports whether the value is a member of any variant enum.`)
		lines.push(`func (p ${u.name}) Valid() bool {`)
		for (const r of u.refs) {
			lines.push(`\tif _, err := Parse${r}(string(p)); err == nil {`)
			lines.push(`\t\treturn true`)
			lines.push(`\t}`)
		}
		lines.push(`\treturn false`)
		lines.push(`}`)
		lines.push('')
	}
	return lines.join('\n')
}

const ENVELOPE_FIELDS = new Set(['name', 'entityId', 'ownerId', 'occurredAt'])

/** Fields that make up an event's payload struct: the model's OWN declarations minus the discriminator + entity id. */
function payloadFieldsOf(ev: ParsedEvent): EventField[] {
	return ev.ownFields.filter(f => f.name !== 'name' && f.name !== 'entityId')
}

/**
 * `// @union` / `// @variant` annotation block for a payload struct — syntax identical to the
 * hand-written medscall style (internal/channel/events/message_received.go), so the pkg/openapi
 * AST scanner grammar matches the STAMPED binding without changes to its parser.
 */
function unionAnnotationLines(ev: ParsedEvent): string[] {
	const lines: string[] = []
	for (const slot of ev.unionSlots) {
		const goDiscs = slot.discriminators.map(pascalToGoField)
		lines.push(`// @union field=${pascalToGoField(slot.field)} discriminatedBy=${goDiscs.join(',')}`)
		for (const v of slot.variants) {
			const pairs = goDiscs.map((d, i) => `${d}=${v.values[i]}`)
			lines.push(`// @variant ${pairs.join(' ')} type=${v.typeName}`)
		}
	}
	return lines
}

export function emitGoEvents(events: ParsedEvent[]): string {
	assertIntegrationWireNames(events)
	const lines: string[] = [HEADER, 'package wire', '']
	const allFields = (e: ParsedEvent) => [...e.fields, ...payloadFieldsOf(e)]
	const needsTime = events.some(e => allFields(e).some(f => f.type.kind === 'date-time'))
	const needsJson = events.some(e => allFields(e).some(f => f.type.kind === 'unknown'))
	const needsUuid = events.some(e => allFields(e).some(f => f.type.kind === 'uuid'))
	const stdImports: string[] = []
	if (needsJson) stdImports.push('"encoding/json"')
	if (needsTime) stdImports.push('"time"')
	const extImports: string[] = []
	if (needsUuid) extImports.push('"github.com/google/uuid"')
	if (stdImports.length + extImports.length > 0) {
		lines.push('import (')
		for (const i of stdImports) lines.push(`\t${i}`)
		if (stdImports.length > 0 && extImports.length > 0) lines.push('')
		for (const i of extImports) lines.push(`\t${i}`)
		lines.push(')')
		lines.push('')
	}

	for (const ev of events) {
		lines.push(`// ${ev.modelName}Name is the wire discriminator for ${ev.modelName}.`)
		lines.push(`const ${ev.modelName}Name = "${ev.wireName}"`)
		lines.push('')
		lines.push(`// ${ev.modelName} — wire shape of ${ev.wireName}.`)
		if (ev.doc) lines.push(`// ${ev.doc}`)
		lines.push(`type ${ev.modelName} struct {`)
		// Name discriminator field first
		lines.push(`\tName       string    \`json:"name"\``)
		// Envelope fields
		lines.push(`\tEntityID   string    \`json:"entityId"\``)
		lines.push(`\tOwnerID    string    \`json:"ownerId"\``)
		lines.push(`\tOccurredAt time.Time \`json:"occurredAt"\``)
		// Payload fields (everything that's not envelope or name)
		for (const f of ev.fields) {
			if (ENVELOPE_FIELDS.has(f.name)) continue
			const goField = pascalToGoField(f.name)
			const ty = goType(f.type)
			// Slices are already nilable — never emit `*[]T`; a nil slice models "absent".
			// json.RawMessage (kind "unknown", the opaque union slots) is a []byte slice too.
			const ptr = f.required || f.type.kind === 'array' || f.type.kind === 'unknown' ? '' : '*'
			const tag = f.required ? f.name : `${f.name},omitempty`
			lines.push(`\t${goField} ${ptr}${ty} \`json:"${tag}"\``)
		}
		lines.push('}')
		lines.push('')
		lines.push(`func (e ${ev.modelName}) EventName() string { return ${ev.modelName}Name }`)
		lines.push('')

		// EVERY event additionally emits a PAYLOAD struct — the verbatim-shaped struct
		// services alias their local payload type to, compatible with the generic
		// `types.IntegrationEvent[Payload]` envelope (the nested `{id, ownerId, time,
		// name, payload}` wire shape the gateway publishes). This is the flat-events
		// generalization of the union-slots pilot bridging: the pilot emitted the
		// payload struct only for union-slotted events; the swap of the remaining
		// hand-rolled envelopes needs the same binding for every event.
		// For union-slotted events the @union/@variant annotations are STAMPED here so
		// the owner's pkg/openapi scanner materializes the complete oneOf from the
		// generated binding instead of a hand-declared struct (union-slots spec §2.2).
		{
			const payloadName = `${ev.modelName.replace(/Event$/, '')}Payload`
			lines.push(`// ${payloadName} — payload of ${ev.wireName}, generated from the contract declaration.`)
			if (ev.unionSlots.length > 0) {
				lines.push('// Union slot fields are opaque (json.RawMessage); the variant SHAPES live in the owner workspace.')
				lines.push(...unionAnnotationLines(ev))
			}
			lines.push(`type ${payloadName} struct {`)
			for (const f of payloadFieldsOf(ev)) {
				const goField = pascalToGoField(f.name)
				const ty = goType(f.type)
				const ptr = f.required || f.type.kind === 'array' || f.type.kind === 'unknown' ? '' : '*'
				// go-playground `required` on a bool rejects the legitimate zero value `false`
				// (a non-group message with isGroup=false would fail struct validation), so
				// boolean flags never carry the tag — verbatim medscall parity: the hand-written
				// payload struct deliberately omitted `required` on IsGroup/FromMe.
				const validated = f.required && f.type.kind !== 'boolean'
				const tag = validated ? `json:"${f.name}" validate:"required"` : f.required ? `json:"${f.name}"` : `json:"${f.name},omitempty"`
				lines.push(`\t${goField} ${ptr}${ty} \`${tag}\``)
			}
			lines.push('}')
			lines.push('')
		}
	}
	return lines.join('\n')
}

export function emitGoEnvelope(events: ParsedEvent[]): string {
	assertIntegrationWireNames(events)
	const lines: string[] = [HEADER, 'package wire', '', 'import (', '\t"encoding/json"', '\t"fmt"', ')', '']
	lines.push('// IntegrationEvent is the discriminator interface — all event structs satisfy it.')
	lines.push('type IntegrationEvent interface {')
	lines.push('\tEventName() string')
	lines.push('}')
	lines.push('')
	lines.push('// UnmarshalIntegrationEvent parses a wire envelope and dispatches to the right struct.')
	lines.push('func UnmarshalIntegrationEvent(data []byte) (IntegrationEvent, error) {')
	lines.push('\tvar discriminator struct {')
	lines.push('\t\tName string `json:"name"`')
	lines.push('\t}')
	lines.push('\tif err := json.Unmarshal(data, &discriminator); err != nil {')
	lines.push('\t\treturn nil, err')
	lines.push('\t}')
	lines.push('\tswitch discriminator.Name {')
	for (const ev of events) {
		lines.push(`\tcase "${ev.wireName}":`)
		lines.push(`\t\tvar v ${ev.modelName}`)
		lines.push('\t\tif err := json.Unmarshal(data, &v); err != nil {')
		lines.push('\t\t\treturn nil, err')
		lines.push('\t\t}')
		lines.push('\t\treturn v, nil')
	}
	lines.push('\tdefault:')
	lines.push('\t\treturn nil, fmt.Errorf("unknown integration event: %q", discriminator.Name)')
	lines.push('\t}')
	lines.push('}')
	lines.push('')
	lines.push('// ParseIntegrationEvent is an alias for UnmarshalIntegrationEvent.')
	lines.push('// It decodes a wire JSON envelope into the concrete typed event by switching on the `name` field.')
	lines.push('func ParseIntegrationEvent(raw []byte) (IntegrationEvent, error) {')
	lines.push('\treturn UnmarshalIntegrationEvent(raw)')
	lines.push('}')
	return `${lines.join('\n')}\n`
}

async function run() {
	const yamlText = await readFile(INPUT, 'utf-8')
	const parsed = parseContractsOpenapi(yamlText)
	// Hard gates BEFORE any rm/write — a bad contract must not wipe the committed bindings.
	assertIntegrationWireNames(parsed.events)
	// Unknown @variant owner = contract compilation error (validated against the WORKSPACES manifest).
	assertUnionSlotOwners(parsed.events, Object.keys(REPO.workspaces))
	await rm(OUTPUT, { recursive: true, force: true })
	await mkdir(OUTPUT, { recursive: true })
	await writeFile(join(OUTPUT, 'enums.go'), emitGoEnums(parsed.enums))
	if (parsed.unions.length > 0) {
		await writeFile(join(OUTPUT, 'unions.go'), emitGoUnions(parsed.unions))
	}
	await writeFile(join(OUTPUT, 'events.go'), emitGoEvents(parsed.events))
	await writeFile(join(OUTPUT, 'envelope.go'), emitGoEnvelope(parsed.events))
	console.log(`✔ emitted Go bindings: ${parsed.enums.length} enums, ${parsed.unions.length} unions, ${parsed.events.length} events`)
}

if (import.meta.main) {
	await run()
}
