import { mkdir, writeFile, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFile } from 'node:fs/promises'
import { parseContractsOpenapi, type ParsedEnum, type ParsedUnion, type ParsedEvent, type FieldType } from './lib/parse-openapi'
import { assertIntegrationWireNames } from './lib/assert-wire-names'
import { REPO } from '../../../template.config'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const INPUT = join(ROOT, 'dist/contracts.openapi.yaml')
const OUTPUT = join(ROOT, 'generated/typescript/src/wire')

const HEADER = `// AUTO-GENERATED by packages/contracts/codegen/emit-wire-ts.ts — do not edit.\n`

function kebab(name: string): string {
	return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

/**
 * Convert an enum value string to a valid TypeScript identifier.
 * For values that are already valid identifiers (e.g. "EXAMPLE"), this is a no-op.
 * For dotted namespaced values (e.g. "sync.external_order_updated"), the leading
 * namespace segment (everything up to and including the first ".") is stripped before
 * uppercasing + replacing remaining non-identifier chars with "_". This currently
 * serves the only dotted enum in the contracts: SyncEventName.
 * "sync.external_order_updated" → strip "sync." → "external_order_updated" → "EXTERNAL_ORDER_UPDATED"
 */
function toTsEnumMember(v: string): string {
	if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(v)) return v
	// Strip the leading namespace segment (up to and including the first dot), then
	// uppercase and replace any remaining non-identifier characters with underscores.
	const stripped = v.includes('.') ? v.slice(v.indexOf('.') + 1) : v
	const ident = stripped.toUpperCase().replace(/[^A-Z0-9_$]/g, '_')
	// A TS enum member name cannot lead with a digit (e.g. "1m" → "1M" is invalid) —
	// prefix "_" so it stays a legal identifier ("1m" → "_1M"). OpenAPI drops the
	// TypeSpec member name, so the label is value-derived; the wire VALUE is exact.
	return /^[0-9]/.test(ident) ? `_${ident}` : ident
}

export function emitTsEnums(enums: ParsedEnum[]): Record<string, string> {
	const files: Record<string, string> = {}
	const indexLines: string[] = []

	for (const e of enums) {
		const file = `${kebab(e.name)}.ts`
		const members = e.values.map(v => `\t${toTsEnumMember(v)} = '${v}',`).join('\n')
		const body = `${HEADER + (e.doc ? `/** ${e.doc} */\n` : '')}export enum ${e.name} {\n${members}\n}\n`
		files[file] = body
		indexLines.push(`export * from './${kebab(e.name)}'`)
	}

	files['index.ts'] = `${HEADER + indexLines.sort().join('\n')}\n`
	return files
}

export function emitTsUnions(unions: ParsedUnion[]): Record<string, string> {
	const files: Record<string, string> = {}
	const indexLines: string[] = []
	for (const u of unions) {
		const members = u.refs.map(r => `z.enum(${r})`).join(', ')
		const body =
			HEADER +
			`import { z } from '${REPO.corePackage}/schema'\n` +
			`import { ${u.refs.join(', ')} } from '../enums'\n\n` +
			(u.doc ? `/** ${u.doc} */\n` : '') +
			`export const ${u.name}Schema = z.union([${members}])\n`
		files[`${kebab(u.name)}.ts`] = body
		indexLines.push(`export * from './${kebab(u.name)}'`)
	}
	files['index.ts'] = `${HEADER + indexLines.sort().join('\n')}\n`
	return files
}

const ENVELOPE_FIELDS = new Set(['name', 'entityId', 'ownerId', 'occurredAt'])

// Enum/union refs can be nested inside array items (e.g. `providers: ProviderKind[]`), so the
// import collector must descend into `array` element types — a top-level-only filter would emit
// `z.array(z.enum(ProviderKind))` without importing ProviderKind. Mirrors zodExpr's recursion.
function collectEnumRefs(t: FieldType): string[] {
	if (t.kind === 'enum-ref') return [t.ref]
	if (t.kind === 'array') return collectEnumRefs(t.items)
	return []
}

function collectUnionRefs(t: FieldType): string[] {
	if (t.kind === 'union-ref') return [t.ref]
	if (t.kind === 'array') return collectUnionRefs(t.items)
	return []
}

function zodExpr(t: FieldType): string {
	switch (t.kind) {
		case 'string':
			return 'z.string()'
		case 'literal':
			return `z.literal('${t.value}')`
		case 'string-enum':
			return `z.enum([${t.values.map(v => `'${v}'`).join(', ')}])`
		case 'enum-ref':
			return `z.enum(${t.ref})`
		case 'union-ref':
			return `${t.ref}Schema`
		case 'boolean':
			return 'z.boolean()'
		case 'integer':
			return 'z.number().int()'
		case 'number':
			return 'z.number()'
		case 'date-time':
			return 'z.date()'
		case 'url':
			return 'z.string().url()'
		case 'array':
			return `z.array(${zodExpr(t.items)})`
		case 'unknown':
			return 'z.unknown()'
	}
}

export function emitTsEvents(events: ParsedEvent[]): Record<string, string> {
	assertIntegrationWireNames(events)
	const files: Record<string, string> = {}

	for (const ev of events) {
		const payloadFields = ev.fields.filter(f => !ENVELOPE_FIELDS.has(f.name))

		const enumRefs = payloadFields.flatMap(f => collectEnumRefs(f.type))
		const enumImports = [...new Set(enumRefs)].sort()
		const importLines = [
			`import { z } from '${REPO.corePackage}/schema'`,
			`import { BaseIntegrationEvent } from '${REPO.corePackage}/events'`,
		]
		if (enumImports.length > 0) {
			const names = enumImports.join(', ')
			importLines.push(`import { ${names} } from '../enums'`)
		}
		const unionRefs = payloadFields.flatMap(f => collectUnionRefs(f.type))
		const unionImports = [...new Set(unionRefs)].sort()
		if (unionImports.length > 0) {
			importLines.push(`import { ${unionImports.map(r => `${r}Schema`).join(', ')} } from '../unions'`)
		}

		const zodFields = payloadFields.map(f => `\t${f.name}: ${zodExpr(f.type)}${f.required ? '' : '.optional()'},`).join('\n')

		const body =
			HEADER +
			importLines.join('\n') +
			'\n\n' +
			(ev.doc ? `/** ${ev.doc} */\n` : '') +
			`export const ${ev.modelName}Schema = z.integrationEvent('${ev.wireName}', {\n${zodFields}\n})\n\n` +
			`export class ${ev.modelName} extends BaseIntegrationEvent<typeof ${ev.modelName}Schema> {\n` +
			`\tstatic override readonly name = '${ev.wireName}' as const\n` +
			`\tstatic readonly schema = ${ev.modelName}Schema\n` +
			`}\n`

		files[`${kebab(ev.modelName.replace(/Event$/, ''))}.ts`] = body
	}

	return files
}

export function emitTsBarrel(events: ParsedEvent[]): string {
	const names = events.map(e => e.modelName)
	const reExports = events
		.map(e => `export * from './${kebab(e.modelName.replace(/Event$/, ''))}'`)
		.sort()
		.join('\n')
	const schemaImports = names.map(n => `\t${n}Schema,`).join('\n')
	const schemas = names.map(n => `\t${n}Schema`).join(',\n')
	return (
		HEADER +
		`import { z } from '${REPO.corePackage}/schema'\n` +
		`import Z from 'zod'\n` +
		`import {\n${schemaImports}\n} from './_imports'\n\n` +
		reExports +
		'\n\n' +
		`export const IntegrationEventSchema = z.discriminatedUnion('name', [\n${schemas},\n])\n` +
		`export type IntegrationEvent = Z.infer<typeof IntegrationEventSchema>\n`
	)
}

async function run() {
	const yamlText = await readFile(INPUT, 'utf-8')
	const parsed = parseContractsOpenapi(yamlText)
	// Hard gate BEFORE any rm/write — a bad contract must not wipe the committed bindings.
	assertIntegrationWireNames(parsed.events)

	const enumDir = join(OUTPUT, 'enums')
	const unionDir = join(OUTPUT, 'unions')
	const eventDir = join(OUTPUT, 'events')
	await rm(enumDir, { recursive: true, force: true })
	await rm(unionDir, { recursive: true, force: true })
	await rm(eventDir, { recursive: true, force: true })
	await mkdir(enumDir, { recursive: true })
	await mkdir(eventDir, { recursive: true })

	const enumFiles = emitTsEnums(parsed.enums)
	for (const [name, contents] of Object.entries(enumFiles)) {
		await writeFile(join(enumDir, name), contents)
	}
	// Only materialize the unions dir when there are unions — a zero-union contract
	// leaves no orphan files (the dir was unconditionally removed above).
	if (parsed.unions.length > 0) {
		await mkdir(unionDir, { recursive: true })
		const unionFiles = emitTsUnions(parsed.unions)
		for (const [name, contents] of Object.entries(unionFiles)) {
			await writeFile(join(unionDir, name), contents)
		}
	}

	const eventFiles = emitTsEvents(parsed.events)
	for (const [name, contents] of Object.entries(eventFiles)) {
		await writeFile(join(eventDir, name), contents)
	}

	const importsRe =
		HEADER +
		parsed.events
			.map(e => `export * from './${kebab(e.modelName.replace(/Event$/, ''))}'`)
			.sort()
			.join('\n') +
		'\n'
	await writeFile(join(eventDir, '_imports.ts'), importsRe)

	await writeFile(join(eventDir, 'index.ts'), emitTsBarrel(parsed.events))

	const unionExport = parsed.unions.length > 0 ? `export * from './unions'\n` : ''
	const wireIndex = `${HEADER}export * from './enums'\n${unionExport}export * from './events'\n`
	await writeFile(join(OUTPUT, 'index.ts'), wireIndex)

	console.log(`✔ emitted ${parsed.enums.length} enums and ${parsed.events.length} events`)
}

if (import.meta.main) {
	await run()
}
