import { mkdir, writeFile, rm, readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseContractsOpenapi, type ParsedEnum, type ParsedUnion, type ParsedEvent, type FieldType } from './lib/parse-openapi'
import { assertIntegrationWireNames } from './lib/assert-wire-names'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const INPUT = join(ROOT, 'dist/contracts.openapi.yaml')
const OUTPUT = join(ROOT, 'generated/go/wire')

const HEADER = `// AUTO-GENERATED by packages/contracts/codegen/emit-wire-go.ts — do not edit.\n`

function pascalToGoField(name: string): string {
	const out = name[0]!.toUpperCase() + name.slice(1)
	return out.replace(/Id\b/g, 'ID').replace(/Url\b/g, 'URL')
}

function goType(t: FieldType): string {
	switch (t.kind) {
		case 'string':
			return 'string'
		case 'literal':
			return 'string'
		case 'string-enum':
			return 'string'
		case 'enum-ref':
			return t.ref
		case 'union-ref':
			return t.ref
		case 'boolean':
			return 'bool'
		case 'integer':
			return t.format === 'int64' ? 'int64' : 'int32'
		case 'number':
			return 'float64'
		case 'date-time':
			return 'time.Time'
		case 'url':
			return 'string'
		case 'array':
			return `[]${goType(t.items)}`
		case 'unknown':
			return 'json.RawMessage'
	}
}

/**
 * Convert an enum value string to a valid Go identifier suffix.
 * For values that are already valid identifiers (e.g. "EXAMPLE"), this is a no-op.
 * For dotted namespaced values (e.g. "sync.external_order_updated"), the leading
 * namespace segment (everything up to and including the first ".") is stripped before
 * uppercasing + replacing remaining non-identifier chars with "_". This currently
 * serves the only dotted enum in the contracts: SyncEventName.
 * "sync.external_order_updated" → strip "sync." → "external_order_updated" → "EXTERNAL_ORDER_UPDATED"
 */
function toGoEnumIdent(v: string): string {
	// If already a valid Go identifier suffix (letters, digits, underscores; no leading digit)
	if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(v)) return v
	// Strip the leading namespace segment (up to and including the first dot), then
	// uppercase and replace any remaining non-identifier characters with underscores.
	const stripped = v.includes('.') ? v.slice(v.indexOf('.') + 1) : v
	return stripped.toUpperCase().replace(/[^A-Z0-9_]/g, '_')
}

export function emitGoEnums(enums: ParsedEnum[]): string {
	const lines: string[] = [HEADER, 'package wire', '', 'import "fmt"', '']
	for (const e of enums) {
		lines.push(`type ${e.name} string`)
		lines.push('')
		lines.push('const (')
		for (const v of e.values) lines.push(`\t${e.name}${toGoEnumIdent(v)} ${e.name} = "${v}"`)
		lines.push(')')
		lines.push('')
		lines.push(`func Parse${e.name}(s string) (${e.name}, error) {`)
		lines.push(`\tswitch ${e.name}(s) {`)
		const cases = e.values.map(v => `${e.name}${toGoEnumIdent(v)}`).join(', ')
		lines.push(`\tcase ${cases}:`)
		lines.push(`\t\treturn ${e.name}(s), nil`)
		lines.push('\tdefault:')
		lines.push(`\t\treturn "", fmt.Errorf("invalid ${e.name}: %q", s)`)
		lines.push('\t}')
		lines.push('}')
		lines.push('')
	}
	return lines.join('\n')
}

export function emitGoUnions(unions: ParsedUnion[]): string {
	const lines: string[] = [HEADER, 'package wire', '']
	for (const u of unions) {
		lines.push(`// ${u.name} is a cross-category union of platform enums.`)
		if (u.doc) lines.push(`// ${u.doc}`)
		// Bridge annotation: read by core/pkg/openapi to emit a oneOf component.
		// `values=` lists the member enum TYPE names (each becomes a $ref).
		lines.push(`// @oneof values=${u.refs.join(',')}`)
		lines.push(`type ${u.name} string`)
		lines.push('')
		lines.push(`// Valid reports whether the value is a member of any variant enum.`)
		lines.push(`func (p ${u.name}) Valid() bool {`)
		for (const r of u.refs) {
			lines.push(`\tif _, err := Parse${r}(string(p)); err == nil {`)
			lines.push(`\t\treturn true`)
			lines.push(`\t}`)
		}
		lines.push(`\treturn false`)
		lines.push(`}`)
		lines.push('')
	}
	return lines.join('\n')
}

const ENVELOPE_FIELDS = new Set(['name', 'entityId', 'ownerId', 'occurredAt'])

export function emitGoEvents(events: ParsedEvent[]): string {
	assertIntegrationWireNames(events)
	const lines: string[] = [HEADER, 'package wire', '']
	const needsTime = events.some(e => e.fields.some(f => f.type.kind === 'date-time'))
	const needsJson = events.some(e => e.fields.some(f => f.type.kind === 'unknown'))
	const imports: string[] = []
	if (needsTime) imports.push('"time"')
	if (needsJson) imports.push('"encoding/json"')
	if (imports.length > 0) {
		lines.push('import (')
		for (const i of imports) lines.push(`\t${i}`)
		lines.push(')')
		lines.push('')
	}

	for (const ev of events) {
		lines.push(`// ${ev.modelName}Name is the wire discriminator for ${ev.modelName}.`)
		lines.push(`const ${ev.modelName}Name = "${ev.wireName}"`)
		lines.push('')
		lines.push(`// ${ev.modelName} — wire shape of ${ev.wireName}.`)
		if (ev.doc) lines.push(`// ${ev.doc}`)
		lines.push(`type ${ev.modelName} struct {`)
		// Name discriminator field first
		lines.push(`\tName       string    \`json:"name"\``)
		// Envelope fields
		lines.push(`\tEntityID   string    \`json:"entityId"\``)
		lines.push(`\tOwnerID    string    \`json:"ownerId"\``)
		lines.push(`\tOccurredAt time.Time \`json:"occurredAt"\``)
		// Payload fields (everything that's not envelope or name)
		for (const f of ev.fields) {
			if (ENVELOPE_FIELDS.has(f.name)) continue
			const goField = pascalToGoField(f.name)
			const ty = goType(f.type)
			// Slices are already nilable — never emit `*[]T`; a nil slice models "absent".
			const ptr = f.required || f.type.kind === 'array' ? '' : '*'
			const tag = f.required ? f.name : `${f.name},omitempty`
			lines.push(`\t${goField} ${ptr}${ty} \`json:"${tag}"\``)
		}
		lines.push('}')
		lines.push('')
		lines.push(`func (e ${ev.modelName}) EventName() string { return ${ev.modelName}Name }`)
		lines.push('')
	}
	return lines.join('\n')
}

export function emitGoEnvelope(events: ParsedEvent[]): string {
	assertIntegrationWireNames(events)
	const lines: string[] = [HEADER, 'package wire', '', 'import (', '\t"encoding/json"', '\t"fmt"', ')', '']
	lines.push('// IntegrationEvent is the discriminator interface — all event structs satisfy it.')
	lines.push('type IntegrationEvent interface {')
	lines.push('\tEventName() string')
	lines.push('}')
	lines.push('')
	lines.push('// UnmarshalIntegrationEvent parses a wire envelope and dispatches to the right struct.')
	lines.push('func UnmarshalIntegrationEvent(data []byte) (IntegrationEvent, error) {')
	lines.push('\tvar discriminator struct {')
	lines.push('\t\tName string `json:"name"`')
	lines.push('\t}')
	lines.push('\tif err := json.Unmarshal(data, &discriminator); err != nil {')
	lines.push('\t\treturn nil, err')
	lines.push('\t}')
	lines.push('\tswitch discriminator.Name {')
	for (const ev of events) {
		lines.push(`\tcase "${ev.wireName}":`)
		lines.push(`\t\tvar v ${ev.modelName}`)
		lines.push('\t\tif err := json.Unmarshal(data, &v); err != nil {')
		lines.push('\t\t\treturn nil, err')
		lines.push('\t\t}')
		lines.push('\t\treturn v, nil')
	}
	lines.push('\tdefault:')
	lines.push('\t\treturn nil, fmt.Errorf("unknown integration event: %q", discriminator.Name)')
	lines.push('\t}')
	lines.push('}')
	lines.push('')
	lines.push('// ParseIntegrationEvent is an alias for UnmarshalIntegrationEvent.')
	lines.push('// It decodes a wire JSON envelope into the concrete typed event by switching on the `name` field.')
	lines.push('func ParseIntegrationEvent(raw []byte) (IntegrationEvent, error) {')
	lines.push('\treturn UnmarshalIntegrationEvent(raw)')
	lines.push('}')
	return `${lines.join('\n')}\n`
}

async function run() {
	const yamlText = await readFile(INPUT, 'utf-8')
	const parsed = parseContractsOpenapi(yamlText)
	// Hard gate BEFORE any rm/write — a bad contract must not wipe the committed bindings.
	assertIntegrationWireNames(parsed.events)
	await rm(OUTPUT, { recursive: true, force: true })
	await mkdir(OUTPUT, { recursive: true })
	await writeFile(join(OUTPUT, 'enums.go'), emitGoEnums(parsed.enums))
	if (parsed.unions.length > 0) {
		await writeFile(join(OUTPUT, 'unions.go'), emitGoUnions(parsed.unions))
	}
	await writeFile(join(OUTPUT, 'events.go'), emitGoEvents(parsed.events))
	await writeFile(join(OUTPUT, 'envelope.go'), emitGoEnvelope(parsed.events))
	console.log(`✔ emitted Go bindings: ${parsed.enums.length} enums, ${parsed.unions.length} unions, ${parsed.events.length} events`)
}

if (import.meta.main) {
	await run()
}
