/**
 * Rust wire emitter — PURE serde structs, no server-framework DSL (rust-wire spec §3.2/F2).
 *
 * The consumer is a CLIENT (the Tauri shell): it deserializes JSON and makes HTTP calls.
 * So the binding depends on serde/serde_json/chrono/uuid/strum only — never on a backend
 * framework crate. If a Rust backend ever wants these events as domain citizens, it wraps
 * the generated struct; the dependency arrow never points the other way.
 *
 * Envelope: the canonical transport `{id, ownerId, time, name, payload}` from
 * lib/envelope.ts (mirror of Go `types.IntegrationEvent[T]`). Payload projection:
 * `payloadFieldsOf` — the same split every other emitter uses.
 *
 * Forward-compat (union-slots spec §2.5): unknown discriminators NEVER fail a parse —
 * `WireEvent::Opaque` catches unknown event names, `Unknown(String)` arms catch unknown
 * union members.
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { assertIntegrationWireNames } from './lib/assert-wire-names'
import { payloadFieldsOf } from './lib/envelope'
import {
	parseContractsOpenapi,
	type EventField,
	type FieldType,
	type ParsedEnum,
	type ParsedEvent,
	type ParsedUnion,
} from './lib/parse-openapi'
import { assertUnionSlotOwners } from './lib/union-slots'
import { REPO } from '../../../template.config'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const INPUT = join(ROOT, 'dist/contracts.openapi.yaml')
const OUTPUT = join(ROOT, 'generated/rust/src/wire')

const HEADER = `// AUTO-GENERATED by packages/contracts/codegen/emit-wire-rs.ts — do not edit.\n`

// ── identifier mechanics ────────────────────────────────────────────────────

/** camelCase → snake_case with acronym handling (`hlsUrl` → `hls_url`). */
function snake(name: string): string {
	return name
		.replace(/([a-z0-9])([A-Z])/g, '$1_$2')
		.replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
		.toLowerCase()
}

/** snake_case → SCREAMING_SNAKE for consts. */
function screaming(name: string): string {
	return snake(name).toUpperCase()
}

const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

/** Keywords that admit a raw identifier (`r#type`). */
const RUST_KEYWORDS = new Set([
	'as', 'async', 'await', 'become', 'box', 'break', 'const', 'continue', 'do', 'dyn', 'else', 'enum',
	'extern', 'false', 'final', 'fn', 'for', 'if', 'impl', 'in', 'let', 'loop', 'macro', 'match', 'mod',
	'move', 'mut', 'override', 'priv', 'pub', 'ref', 'return', 'static', 'struct', 'trait', 'true', 'try',
	'type', 'typeof', 'unsafe', 'unsized', 'use', 'virtual', 'where', 'while', 'yield',
])
/** Keywords a raw ident CANNOT spell — suffixed `_` + explicit serde rename instead. */
const RUST_NON_RAWABLE = new Set(['self', 'super', 'crate'])

interface RsField {
	/** The emitted Rust identifier (possibly `r#`-prefixed or `_`-suffixed). */
	ident: string
	/** Explicit `#[serde(rename)]` needed when rename_all=camelCase cannot recover the wire name. */
	explicitRename: string | null
}

/** Rust field ident for a wire (camelCase) property name. rename_all = "camelCase" on the
 *  struct recovers the wire name from a plain snake_case ident, so most fields need no
 *  explicit rename; `_`-suffixed non-rawable keywords do. */
function rsField(wireName: string): RsField {
	const s = snake(wireName)
	if (RUST_NON_RAWABLE.has(s)) return { ident: `${s}_`, explicitRename: wireName }
	if (RUST_KEYWORDS.has(s)) return { ident: `r#${s}`, explicitRename: null }
	return { ident: s, explicitRename: null }
}

/**
 * Enum variant ident for a wire value — same convention as toGoEnumIdent/toTsEnumMember:
 * already-valid identifiers pass through; dotted values drop the leading namespace
 * segment; remaining non-identifier chars become `_`; digit-leading gains a `_` prefix.
 * The WIRE value is always carried exactly by `#[serde(rename)]` / `#[strum(serialize)]`.
 */
function rsEnumVariant(v: string): string {
	if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(v)) return v
	const stripped = v.includes('.') ? v.slice(v.indexOf('.') + 1) : v
	const ident = stripped.toUpperCase().replace(/[^A-Z0-9_]/g, '_')
	return /^[0-9]/.test(ident) ? `_${ident}` : ident
}

// ── type mapping ────────────────────────────────────────────────────────────

/** FieldType → Rust type. `localEnum` names the per-field enum for inline string-enums. */
function rsType(t: FieldType, localEnum?: string): string {
	switch (t.kind) {
		case 'string':
		case 'url':
		case 'literal':
			return 'String'
		case 'uuid':
			return 'uuid::Uuid'
		case 'string-enum':
			if (!localEnum) throw new Error('string-enum field without a local enum name')
			return localEnum
		case 'enum-ref':
			return t.ref
		case 'union-ref':
			return t.ref
		case 'boolean':
			return 'bool'
		case 'integer':
			return t.format === 'int32' ? 'i32' : 'i64'
		case 'number':
			// TypeSpec float32 reaches OpenAPI as `format: float` (single precision).
			return t.format === 'float' || t.format === 'float32' ? 'f32' : 'f64'
		case 'date-time':
			return 'chrono::DateTime<chrono::Utc>'
		case 'array':
			return `Vec<${rsType(t.items, localEnum)}>`
		case 'unknown':
			return 'serde_json::Value'
	}
}

const DERIVES = '#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]'

const ENUM_DERIVES = [
	'#[derive(',
	'\tDebug, Clone, Copy, PartialEq, Eq, Hash,',
	'\tserde::Serialize, serde::Deserialize,',
	'\tstrum::EnumString, strum::IntoStaticStr, strum::Display,',
	')]',
]

/** One enum body: derives + per-variant serde/strum renames carrying the exact wire value. */
function enumBlock(name: string, values: string[], doc?: string): string[] {
	const lines: string[] = []
	if (doc) lines.push(`/// ${doc}`)
	lines.push(...ENUM_DERIVES)
	lines.push('#[allow(non_camel_case_types)]')
	lines.push(`pub enum ${name} {`)
	for (const v of values) {
		lines.push(`\t#[serde(rename = "${v}")]`)
		lines.push(`\t#[strum(serialize = "${v}")]`)
		lines.push(`\t${rsEnumVariant(v)},`)
	}
	lines.push('}')
	return lines
}

// ── emitters ────────────────────────────────────────────────────────────────

export function emitRsEnums(enums: ParsedEnum[]): string {
	const lines: string[] = [HEADER]
	for (const e of enums) {
		lines.push('')
		lines.push(...enumBlock(e.name, e.values, e.doc))
	}
	return `${lines.join('\n')}\n`
}

/**
 * Closed contract unions (oneOf of enum $refs). Untagged: serde tries each member enum in
 * order; an unrecognized value lands in `Unknown(String)` — forward-compat, never a parse
 * failure (mirror of the Go union's permissive `string` + advisory `Valid()`).
 */
export function emitRsUnions(unions: ParsedUnion[]): string {
	const lines: string[] = [HEADER, 'use super::enums::*;', '']
	for (const u of unions) {
		if (u.doc) lines.push(`/// ${u.doc}`)
		lines.push('/// Untagged union of member enums; unknown values land in `Unknown` (forward-compat).')
		lines.push(DERIVES)
		lines.push('#[serde(untagged)]')
		lines.push(`pub enum ${u.name} {`)
		for (const r of u.refs) lines.push(`\t${r}(${r}),`)
		lines.push('\tUnknown(String),')
		lines.push('}')
		lines.push('')
		lines.push(`impl ${u.name} {`)
		lines.push('\tpub fn as_str(&self) -> &str {')
		lines.push('\t\tmatch self {')
		for (const r of u.refs) lines.push(`\t\t\tSelf::${r}(v) => <&'static str>::from(v),`)
		lines.push('\t\t\tSelf::Unknown(s) => s,')
		lines.push('\t\t}')
		lines.push('\t}')
		lines.push('')
		lines.push('\tpub fn is_known(&self) -> bool {')
		lines.push('\t\t!matches!(self, Self::Unknown(_))')
		lines.push('\t}')
		lines.push('}')
		lines.push('')
	}
	return `${lines.join('\n')}\n`
}

/** Name of the local enum generated for an inline string-enum payload field. */
function localEnumName(modelName: string, fieldName: string): string {
	return modelName.replace(/Event$/, '') + pascal(snake(fieldName).replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase()))
}

function fieldLines(ev: ParsedEvent, f: EventField): string[] {
	const lines: string[] = []
	const { ident, explicitRename } = rsField(f.name)
	const local = f.type.kind === 'string-enum' || (f.type.kind === 'array' && f.type.items.kind === 'string-enum')
		? localEnumName(ev.modelName, f.name)
		: undefined
	const base = rsType(f.type, local)
	const slot = ev.unionSlots.find(s => s.field === f.name)

	if (f.doc) lines.push(`\t/// ${f.doc}`)
	if (f.type.kind === 'literal') lines.push(`\t/// Always \`"${f.type.value}"\`.`)
	if (slot) {
		const variants = slot.variants.map(v => `${v.typeName} (${v.owner})`).join(', ')
		lines.push(`\t/// Opaque union slot discriminated by [${slot.discriminators.join(', ')}] — variant shapes live`)
		lines.push(`\t/// with the owner workspace: ${variants}. See union-slots spec §6.`)
	}

	if (explicitRename) lines.push(`\t#[serde(rename = "${explicitRename}")]`)

	if (f.type.kind === 'array') {
		// Arrays mirror Go nil-slice semantics: absent == empty, never Option<Vec<T>>.
		if (!f.required) lines.push(`\t#[serde(default, skip_serializing_if = "Vec::is_empty")]`)
		lines.push(`\tpub ${ident}: ${base},`)
		return lines
	}
	if (!f.required) {
		lines.push(`\t#[serde(skip_serializing_if = "Option::is_none")]`)
		lines.push(`\tpub ${ident}: Option<${base}>,`)
		return lines
	}
	lines.push(`\tpub ${ident}: ${base},`)
	return lines
}

export function emitRsEvents(events: ParsedEvent[]): string {
	assertIntegrationWireNames(events)
	const lines: string[] = [
		HEADER,
		'#[allow(unused_imports)]',
		'use super::enums::*;',
		'#[allow(unused_imports)]',
		'use super::unions::*;',
		'',
	]

	for (const ev of events) {
		const model = ev.modelName.replace(/Event$/, '')
		const payloadName = `${model}Payload`
		const fields = payloadFieldsOf(ev)

		// Inline string-enums first: one local enum per field, exact wire renames.
		for (const f of fields) {
			const inline = f.type.kind === 'string-enum' ? f.type : f.type.kind === 'array' && f.type.items.kind === 'string-enum' ? f.type.items : null
			if (inline) {
				lines.push(...enumBlock(localEnumName(ev.modelName, f.name), inline.values, f.doc))
				lines.push('')
			}
		}

		lines.push(`/// Wire discriminator for [\`${payloadName}\`].`)
		lines.push(`pub const ${screaming(ev.modelName)}_NAME: &str = "${ev.wireName}";`)
		lines.push('')
		if (ev.doc) lines.push(`/// ${ev.doc}`)
		lines.push(`/// Payload of \`${ev.wireName}\`, generated from the contract declaration.`)
		lines.push(DERIVES)
		lines.push('#[serde(rename_all = "camelCase")]')
		lines.push(`pub struct ${payloadName} {`)
		for (const f of fields) lines.push(...fieldLines(ev, f))
		lines.push('}')
		lines.push('')
		lines.push(`/// \`${ev.wireName}\` in the canonical transport envelope.`)
		lines.push(`pub type ${ev.modelName} = super::envelope::Envelope<${payloadName}>;`)
		lines.push('')
	}
	return lines.join('\n')
}

export function emitRsEnvelope(events: ParsedEvent[]): string {
	assertIntegrationWireNames(events)
	const lines: string[] = [
		HEADER,
		'#[allow(unused_imports)]',
		'use super::events::*;',
		'',
		'/// The canonical transport envelope — mirror of Go `types.IntegrationEvent[T]`',
		'/// (`{id, ownerId, time, name, payload}`): what every service publishes and consumes.',
		DERIVES,
		'#[serde(rename_all = "camelCase")]',
		'pub struct Envelope<T> {',
		'\tpub id: uuid::Uuid,',
		'\tpub owner_id: String,',
		'\tpub time: chrono::DateTime<chrono::Utc>,',
		'\tpub name: String,',
		'\tpub payload: T,',
		'}',
		'',
		'/// Discriminated union of all integration events, tagged by the wire `name`.',
		'/// Each variant carries the FULL transport envelope — `id` and `time` included.',
		DERIVES,
		'#[serde(tag = "name")]',
		'pub enum IntegrationEvent {',
	]
	for (const ev of events) {
		const model = ev.modelName.replace(/Event$/, '')
		lines.push(`\t#[serde(rename = "${ev.wireName}", rename_all = "camelCase")]`)
		lines.push(`\t${model} {`)
		lines.push('\t\tid: uuid::Uuid,')
		lines.push('\t\towner_id: String,')
		lines.push('\t\ttime: chrono::DateTime<chrono::Utc>,')
		lines.push(`\t\tpayload: super::events::${model}Payload,`)
		lines.push('\t},')
	}
	lines.push('}')
	lines.push('')
	lines.push('impl IntegrationEvent {')
	lines.push('\t/// The wire discriminator of this event.')
	lines.push("\tpub fn name(&self) -> &'static str {")
	lines.push('\t\tmatch self {')
	for (const ev of events) {
		const model = ev.modelName.replace(/Event$/, '')
		lines.push(`\t\t\tSelf::${model} { .. } => super::events::${screaming(ev.modelName)}_NAME,`)
	}
	lines.push('\t\t}')
	lines.push('\t}')
	lines.push('')
	lines.push('\t/// The tenant / owner this event belongs to.')
	lines.push('\tpub fn owner_id(&self) -> &str {')
	lines.push('\t\tmatch self {')
	for (const ev of events) {
		const model = ev.modelName.replace(/Event$/, '')
		lines.push(`\t\t\tSelf::${model} { owner_id, .. } => owner_id,`)
	}
	lines.push('\t\t}')
	lines.push('\t}')
	lines.push('}')
	lines.push('')
	lines.push('/// Forward-compat wrapper (union-slots spec §2.5): an unknown event `name` parses as')
	lines.push('/// `Opaque` — log + passthrough, never an error. New variants published by another')
	lines.push('/// service MUST NOT break old consumers.')
	lines.push('#[derive(Debug, Clone, PartialEq, serde::Serialize)]')
	lines.push('#[serde(untagged)]')
	lines.push('pub enum WireEvent {')
	lines.push('\tKnown(IntegrationEvent),')
	lines.push('\tOpaque(serde_json::Value),')
	lines.push('}')
	lines.push('')
	lines.push("impl<'de> serde::Deserialize<'de> for WireEvent {")
	lines.push('\tfn deserialize<D: serde::Deserializer<\'de>>(de: D) -> Result<Self, D::Error> {')
	lines.push('\t\tlet raw = serde_json::Value::deserialize(de)?;')
	lines.push('\t\tmatch serde_json::from_value::<IntegrationEvent>(raw.clone()) {')
	lines.push('\t\t\tOk(ev) => Ok(WireEvent::Known(ev)),')
	lines.push('\t\t\tErr(_) => Ok(WireEvent::Opaque(raw)),')
	lines.push('\t\t}')
	lines.push('\t}')
	lines.push('}')
	return `${lines.join('\n')}\n`
}

/**
 * Union-slot MANIFEST (union-slots spec §2.2) — the Rust twin of the TS `<Model>Unions`
 * export: slot → discriminators → [{values, typeName, owner}]. Machine-readable consts a
 * consumer (or the union-parity rail) can walk; the variant SHAPES stay with the owner
 * workspace and reach Rust only through the owner's generated client (decode via
 * `crate::slot::Slot`).
 */
export function emitRsSlots(events: ParsedEvent[]): string {
	const slotted = events.filter(ev => ev.unionSlots.length > 0).sort((a, b) => a.modelName.localeCompare(b.modelName))
	const lines: string[] = [
		HEADER,
		'/// One union slot on an event payload: which field, discriminated by what, with',
		'/// which declared variants. Shapes are NOT here (union-slots spec §6) — decode the',
		'/// opaque value with [`crate::slot::Slot`] against the owner-client type.',
		'#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
		'pub struct UnionSlotMeta {',
		"\tpub field: &'static str,",
		"\tpub discriminators: &'static [&'static str],",
		"\tpub variants: &'static [UnionVariantMeta],",
		'}',
		'',
		'/// One declared variant: discriminator values (positional, zipped with the slot',
		"/// discriminators), the owner-workspace type name, and the owner's WORKSPACES id.",
		'#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
		'pub struct UnionVariantMeta {',
		"\tpub values: &'static [&'static str],",
		"\tpub type_name: &'static str,",
		"\tpub owner: &'static str,",
		'}',
		'',
	]
	if (slotted.length === 0) {
		lines.push('// no union-slotted events declared in the contract')
		return `${lines.join('\n')}\n`
	}
	for (const ev of slotted) {
		lines.push(`/// Union-slot manifest of \`${ev.wireName}\`.`)
		lines.push(`pub const ${screaming(ev.modelName)}_SLOTS: &[UnionSlotMeta] = &[`)
		for (const slot of ev.unionSlots) {
			lines.push('\tUnionSlotMeta {')
			lines.push(`\t\tfield: "${slot.field}",`)
			lines.push(`\t\tdiscriminators: &[${slot.discriminators.map(d => `"${d}"`).join(', ')}],`)
			lines.push('\t\tvariants: &[')
			for (const v of slot.variants) {
				lines.push(
					`\t\t\tUnionVariantMeta { values: &[${v.values.map(x => `"${x}"`).join(', ')}], type_name: "${v.typeName}", owner: "${v.owner}" },`,
				)
			}
			lines.push('\t\t],')
			lines.push('\t},')
		}
		lines.push('];')
		lines.push('')
	}
	return lines.join('\n')
}

async function run() {
	const yamlText = await readFile(INPUT, 'utf-8')
	const parsed = parseContractsOpenapi(yamlText)
	// Hard gates BEFORE any rm/write — a bad contract must not wipe the committed bindings.
	assertIntegrationWireNames(parsed.events)
	assertUnionSlotOwners(parsed.events, Object.keys(REPO.workspaces))
	await rm(OUTPUT, { recursive: true, force: true })
	await mkdir(OUTPUT, { recursive: true })
	await writeFile(join(OUTPUT, 'enums.rs'), emitRsEnums(parsed.enums))
	// unions.rs is always written (mod.rs declares it unconditionally); empty contract → header only.
	await writeFile(join(OUTPUT, 'unions.rs'), parsed.unions.length > 0 ? emitRsUnions(parsed.unions) : `${HEADER}// no unions declared in the contract\n`)
	await writeFile(join(OUTPUT, 'events.rs'), emitRsEvents(parsed.events))
	await writeFile(join(OUTPUT, 'envelope.rs'), emitRsEnvelope(parsed.events))
	await writeFile(join(OUTPUT, 'slots.rs'), emitRsSlots(parsed.events))
	await writeFile(join(OUTPUT, 'mod.rs'), `${HEADER}pub mod enums;\npub mod unions;\npub mod events;\npub mod envelope;\npub mod slots;\n`)
	console.log(`✔ emitted Rust bindings: ${parsed.enums.length} enums, ${parsed.unions.length} unions, ${parsed.events.length} events`)
}

if (import.meta.main) {
	await run()
}
