import { useState } from 'react'
import { motion } from 'motion/react'
import { Link, useRouterState } from '@tanstack/react-router'
import { useTranslation } from 'react-i18next'
import { cva } from 'class-variance-authority'

import { cn } from '@/lib/utils'
import { auth } from '@/lib'
import { useSidebarStore } from '@/components/Navbar/stores/useSidebarStore'
import { Button } from '@/components/ui/button'
import { GradientIcon } from '@/components/ui/gradient-icon'
import type { FileRouteTypes } from '@/routeTree.gen'
import {
	BkLogoIcon,
	ChevronRightIcon,
	EngineIcon,
	HomeIcon,
	TurnoffIcon,
	UserIcon,
	IconComponent,
} from '@/components/ui/icons'

/** Type-safe route paths generated by TanStack Router. */
type AppRoute = FileRouteTypes['to']

export interface NavigationItem {
	label: string
	icon: IconComponent
	/** Absolute route. If omitted (or `disabled` is true) the item renders as a static, non-clickable row. */
	path?: AppRoute
	/** Coming-soon items: greyed out, no pointer events. */
	disabled?: boolean
	/** Children render nested below the parent when the parent is expanded. */
	children?: NavigationItem[]
}

function getNavigationItems(t: ReturnType<typeof useTranslation>['t']): NavigationItem[] {
	return [
		{ label: t('nav.home'), icon: HomeIcon, path: '/dashboard' },
		{
			label: t('nav.settings'),
			icon: EngineIcon,
			children: [
				{ label: t('nav.account'), icon: UserIcon, path: '/settings/account' },
			],
		},
	]
}

const TRANSITION = {
	duration: 0.3,
	ease: [0.4, 0, 0.2, 1] as const,
}

const navRow = cva('flex items-center rounded-lg gap-3 h-10 transition-colors', {
	variants: {
		nested: {
			false: 'px-3',
			true: 'pl-9 pr-3',
		},
		state: {
			default:
				'text-sidebar-foreground/70 hover:text-sidebar-foreground hover:bg-[linear-gradient(to_right,oklch(from_var(--sidebar-foreground)_l_c_h_/_0.18),transparent)]',
			active: 'bg-[linear-gradient(to_right,oklch(from_var(--sidebar-foreground)_l_c_h_/_0.1),transparent)] text-sidebar-foreground',
			disabled: 'opacity-40 text-sidebar-foreground/70 pointer-events-none',
		},
	},
	defaultVariants: { nested: false, state: 'default' },
})

export type SidebarProps = React.ComponentProps<'aside'>

export function Sidebar({ className }: SidebarProps) {
	const state = useRouterState()
	const { t } = useTranslation()
	const activeRoute = state.location.pathname
	const { isExpanded, setIsExpanded } = useSidebarStore()
	const [openGroups, setOpenGroups] = useState<Record<string, boolean>>({})

	const handleLogout = async () => {
		await auth.signOut()
		window.location.href = '/sign-in'
	}

	const items = getNavigationItems(t)

	const toggleGroup = (label: string) => setOpenGroups(prev => ({ ...prev, [label]: !prev[label] }))

	return (
		<motion.aside
			className={cn('bg-sidebar flex flex-col py-6 px-3 gap-6 z-30 shrink-0 overflow-y-auto overflow-x-hidden', className)}
			initial={false}
			animate={{ width: isExpanded ? '16rem' : '5rem' }}
			transition={TRANSITION}
			onMouseEnter={() => setIsExpanded(true)}
			onMouseLeave={() => setIsExpanded(false)}
		>
			<LogoSection isExpanded={isExpanded} />

			<nav className="flex flex-col gap-1">
				{items.map(item => (
					<NavigationEntry
						key={item.label}
						item={item}
						isExpanded={isExpanded}
						activeRoute={activeRoute}
						isOpen={!!openGroups[item.label]}
						onToggle={() => toggleGroup(item.label)}
					/>
				))}
			</nav>

			<LogoutSection isExpanded={isExpanded} onLogout={handleLogout} />
		</motion.aside>
	)
}

function LogoSection({ isExpanded }: { isExpanded: boolean }) {
	return (
		<div className="flex items-center gap-2.5 h-10 px-2">
			<GradientIcon icon={BkLogoIcon} className="size-7 text-sidebar-foreground shrink-0" />
			<motion.span
				className="text-lg font-semibold text-sidebar-foreground whitespace-nowrap font-serif tracking-tight"
				initial={false}
				animate={{ opacity: isExpanded ? 1 : 0 }}
				transition={TRANSITION}
			>
				Dash
			</motion.span>
		</div>
	)
}

interface NavigationEntryProps {
	item: NavigationItem
	isExpanded: boolean
	activeRoute?: string
	isOpen: boolean
	onToggle: () => void
	depth?: number
}

/**
 * Top-level entry. Renders either:
 *   - a Link (item has `path`, not disabled),
 *   - a button (item has `children`, toggles its nested list),
 *   - a static row (item has neither — acts as placeholder / disabled).
 */
function NavigationEntry({ item, isExpanded, activeRoute, isOpen, onToggle, depth = 0 }: NavigationEntryProps) {
	const { t } = useTranslation()
	const hasChildren = !!item.children && item.children.length > 0
	const isActive = item.path ? activeRoute === item.path || activeRoute?.startsWith(`${item.path}/`) : false

	const sharedRow = <EntryContent item={item} isExpanded={isExpanded} hasChildren={hasChildren} isOpen={isOpen} depth={depth} />

	const state = item.disabled ? 'disabled' : isActive ? 'active' : 'default'
	const rowClass = navRow({ nested: depth > 0, state })

	if (hasChildren) {
		return (
			<>
				<button
					type="button"
					onClick={item.disabled ? undefined : onToggle}
					className={cn(rowClass, 'w-full text-left cursor-pointer')}
					aria-label={item.label}
					aria-expanded={isOpen}
					title={item.label}
					disabled={item.disabled}
				>
					{sharedRow}
				</button>
				{isOpen && isExpanded && (
					<div className="flex flex-col gap-1 mt-1 mb-2">
						{item.children!.map(child => (
							<NavigationEntry
								key={child.label}
								item={child}
								isExpanded={isExpanded}
								activeRoute={activeRoute}
								isOpen={false}
								onToggle={() => undefined}
								depth={depth + 1}
							/>
						))}
					</div>
				)}
			</>
		)
	}

	if (item.path && !item.disabled) {
		return (
			<Link to={item.path} className={rowClass} aria-label={item.label} title={item.label}>
				{sharedRow}
			</Link>
		)
	}

	return (
		// biome-ignore lint/a11y/useAriaPropsSupportedByRole: <explanation>
		<div className={rowClass} aria-label={item.label} title={item.disabled ? `${item.label} — ${t('nav.comingSoon')}` : item.label}>
			{sharedRow}
		</div>
	)
}

function EntryContent({
	item,
	isExpanded,
	hasChildren,
	isOpen,
	depth,
}: {
	item: NavigationItem
	isExpanded: boolean
	hasChildren: boolean
	isOpen: boolean
	depth: number
}) {
	return (
		<>
			<GradientIcon icon={item.icon} className={cn(depth === 0 ? 'size-5' : 'size-4', 'shrink-0')} />
			<motion.span
				className="text-sm font-medium whitespace-nowrap flex-1 truncate"
				initial={false}
				animate={{ opacity: isExpanded ? 1 : 0 }}
				transition={TRANSITION}
			>
				{item.label}
			</motion.span>
			{hasChildren && (
				<motion.span
					initial={false}
					animate={{ opacity: isExpanded ? 1 : 0, rotate: isOpen ? 90 : 0 }}
					transition={TRANSITION}
					className="shrink-0"
				>
					<ChevronRightIcon className="size-4" />
				</motion.span>
			)}
		</>
	)
}

function LogoutSection({ isExpanded, onLogout }: { isExpanded: boolean; onLogout: () => void }) {
	const { t } = useTranslation()
	return (
		<div className="mt-auto mb-4">
			<Button
				variant="ghost"
				onClick={onLogout}
				className="flex items-center justify-start text-sidebar-foreground/70 hover:text-sidebar-foreground hover:bg-[linear-gradient(to_right,oklch(from_var(--sidebar-foreground)_l_c_h_/_0.18),transparent)] gap-3 h-10 px-3 w-full"
				aria-label={t('common.logout')}
			>
				<GradientIcon icon={TurnoffIcon} className="size-5 shrink-0" />
				<motion.span
					className="text-sm font-medium whitespace-nowrap"
					initial={false}
					animate={{ opacity: isExpanded ? 1 : 0 }}
					transition={TRANSITION}
				>
					{t('common.logout')}
				</motion.span>
			</Button>
		</div>
	)
}
