ALTER TABLE chats ADD COLUMN IF NOT EXISTS unread_messages INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS last_message_timestamp TEXT NOT NULL DEFAULT '';
ALTER TABLE chats ADD COLUMN IF NOT EXISTS muted BOOLEAN NOT NULL DEFAULT false;
